"""Equity APIs 1-30 — master data, prices, indices, market stats."""

# Each API: dict with num, name, url, freq, update, inputs (list of (name, desc)),
# outputs (list of (name, dtype, desc))

EQUITY_APIS_1_30 = [
    {
        "num": 1, "name": "Company Master", "url": "/v1/company-master",
        "freq": "EOD", "update": "18:00 IST daily",
        "inputs": [
            ("symbol", "NSE trading symbol (optional)"),
            ("bse_code", "BSE numeric security code (optional)"),
            ("isin", "12-char ISIN (optional)"),
            ("sector", "Filter by GICS sector (optional)"),
            ("is_active", "Currently traded flag (default true)"),
            ("page,limit", "Pagination controls"),
        ],
        "outputs": [
            ("company_id", "INTEGER", "Internal surrogate primary key"),
            ("company_name", "VARCHAR(255)", "Full registered company name"),
            ("short_name", "VARCHAR(100)", "Trading or brand name"),
            ("bse_code", "INTEGER", "BSE numeric security code"),
            ("nse_symbol", "VARCHAR(20)", "NSE trading symbol"),
            ("isin", "CHAR(12)", "International Securities Identification Number"),
            ("face_value", "NUMERIC(10,2)", "Face value per share in INR"),
            ("sector", "VARCHAR(100)", "GICS-mapped sector classification"),
            ("industry", "VARCHAR(100)", "Industry classification"),
            ("sub_industry", "VARCHAR(100)", "Granular sub-industry"),
            ("market_cap_cr", "NUMERIC(18,2)", "Market capitalization in INR crores"),
            ("market_cap_category", "VARCHAR(20)", "Large/Mid/Small/Micro cap classification"),
            ("listing_date_nse", "DATE", "First date of listing on NSE"),
            ("listing_date_bse", "DATE", "First date of listing on BSE"),
            ("incorporation_date", "DATE", "Date of company incorporation"),
            ("cin", "CHAR(21)", "Corporate Identification Number from MCA"),
            ("is_active", "BOOLEAN", "Currently traded flag"),
            ("is_in_nifty50", "BOOLEAN", "Nifty 50 constituent flag"),
            ("is_in_sensex", "BOOLEAN", "Sensex constituent flag"),
            ("is_fno_enabled", "BOOLEAN", "F&O eligibility flag"),
            ("updated_at", "TIMESTAMPTZ", "Last warehouse update timestamp UTC"),
        ],
    },
    {
        "num": 2, "name": "Company Profile", "url": "/v1/company/{symbol}/profile",
        "freq": "Weekly", "update": "Sunday 02:00 IST",
        "inputs": [("symbol", "NSE symbol (path, required)")],
        "outputs": [
            ("symbol", "VARCHAR(20)", "NSE symbol primary key"),
            ("business_description", "TEXT", "Long-form business summary"),
            ("business_segments", "JSONB", "Array of business segment dicts with revenue %"),
            ("geographic_segments", "JSONB", "Array of geographic segments with revenue %"),
            ("key_products", "TEXT[]", "Top product or service names"),
            ("competitive_position", "TEXT", "Market leadership notes"),
            ("website", "VARCHAR(255)", "Corporate website URL"),
            ("email", "VARCHAR(255)", "Investor relations email"),
            ("phone", "VARCHAR(50)", "Main switchboard number"),
            ("employee_count", "INTEGER", "Latest disclosed headcount"),
            ("founded_year", "SMALLINT", "Year of incorporation"),
            ("headquarters_city", "VARCHAR(100)", "Registered HQ city"),
            ("headquarters_state", "VARCHAR(100)", "Registered HQ state"),
            ("headquarters_country", "VARCHAR(100)", "Country (always India)"),
            ("chairperson", "VARCHAR(200)", "Current chairperson name"),
            ("managing_director", "VARCHAR(200)", "Current MD or CEO name"),
            ("updated_at", "TIMESTAMPTZ", "Last refresh timestamp"),
        ],
    },
    {
        "num": 3, "name": "Listed Securities", "url": "/v1/listed-securities",
        "freq": "EOD", "update": "18:00 IST daily",
        "inputs": [
            ("exchange", "NSE/BSE/BOTH filter"),
            ("series", "Trading series (EQ/BE/BZ/SM for NSE; A/B/T/Z for BSE)"),
            ("as_of_date", "Snapshot date (optional)"),
            ("page,limit", "Pagination controls"),
        ],
        "outputs": [
            ("security_id", "BIGINT", "Primary key"),
            ("symbol", "VARCHAR(20)", "NSE symbol or BSE scrip-id"),
            ("bse_code", "INTEGER", "BSE numeric code (nullable)"),
            ("nse_symbol", "VARCHAR(20)", "NSE symbol (nullable)"),
            ("isin", "CHAR(12)", "ISIN identifier"),
            ("series", "VARCHAR(5)", "Trading series code"),
            ("exchange", "VARCHAR(5)", "NSE or BSE"),
            ("lot_size", "INTEGER", "Marketable lot size"),
            ("face_value", "NUMERIC(10,2)", "Face value per share"),
            ("listing_date", "DATE", "Date of listing on that exchange"),
            ("delisting_date", "DATE", "Date of delisting if any"),
            ("is_suspended", "BOOLEAN", "Currently suspended flag"),
            ("circuit_band_pct", "NUMERIC(5,2)", "Daily price band percentage"),
            ("updated_at", "TIMESTAMPTZ", "Last update timestamp"),
        ],
    },
    {
        "num": 4, "name": "Industry Classification", "url": "/v1/industry-classification",
        "freq": "Monthly", "update": "1st of month 02:00 IST",
        "inputs": [
            ("level", "Filter by sector/industry/sub_industry"),
            ("parent_code", "Parent classification code"),
        ],
        "outputs": [
            ("code", "VARCHAR(20)", "Classification code (primary key)"),
            ("name", "VARCHAR(200)", "Display name"),
            ("level", "VARCHAR(20)", "Hierarchy level"),
            ("parent_code", "VARCHAR(20)", "Parent code reference"),
            ("company_count", "INTEGER", "Number of listed companies in classification"),
            ("total_market_cap_cr", "NUMERIC(18,2)", "Aggregate market cap of constituents"),
            ("description", "TEXT", "Industry description"),
            ("updated_at", "TIMESTAMPTZ", "Last update"),
        ],
    },
    {
        "num": 5, "name": "Board of Directors", "url": "/v1/company/{symbol}/directors",
        "freq": "Quarterly", "update": "Within 7 days of shareholding pattern release",
        "inputs": [
            ("symbol", "NSE symbol (path, required)"),
            ("active_only", "Exclude resigned directors (default true)"),
        ],
        "outputs": [
            ("director_id", "BIGINT", "Primary key"),
            ("symbol", "VARCHAR(20)", "Company symbol"),
            ("name", "VARCHAR(200)", "Full director name"),
            ("din", "CHAR(8)", "Director Identification Number from MCA"),
            ("designation", "VARCHAR(100)", "MD/Chairman/Whole-Time/Independent/Nominee"),
            ("category", "VARCHAR(50)", "Executive/Non-Executive/Independent"),
            ("appointment_date", "DATE", "Date of appointment to current role"),
            ("cessation_date", "DATE", "Date of resignation if applicable"),
            ("age", "SMALLINT", "Age in years"),
            ("nationality", "VARCHAR(50)", "Director nationality"),
            ("other_directorships", "SMALLINT", "Count of other listed company boards"),
            ("shareholding_count", "BIGINT", "Shares held in this company"),
            ("shareholding_pct", "NUMERIC(8,4)", "Percentage of total equity held"),
            ("updated_at", "TIMESTAMPTZ", "Last update timestamp"),
        ],
    },
    {
        "num": 6, "name": "Key Management Personnel", "url": "/v1/company/{symbol}/kmp",
        "freq": "Quarterly", "update": "With directors update",
        "inputs": [("symbol", "NSE symbol (path)")],
        "outputs": [
            ("kmp_id", "BIGINT", "Primary key"),
            ("symbol", "VARCHAR(20)", "Company symbol"),
            ("name", "VARCHAR(200)", "Full name"),
            ("designation", "VARCHAR(100)", "CFO/CS/CTO/COO etc"),
            ("appointment_date", "DATE", "Appointment date"),
            ("qualification", "VARCHAR(500)", "Educational qualification"),
            ("experience_years", "SMALLINT", "Years of experience"),
            ("prior_company", "VARCHAR(200)", "Previous employer"),
            ("updated_at", "TIMESTAMPTZ", "Last update"),
        ],
    },
    {
        "num": 7, "name": "Subsidiaries & Associates", "url": "/v1/company/{symbol}/subsidiaries",
        "freq": "Annual", "update": "Within 30 days of AGM",
        "inputs": [
            ("symbol", "NSE symbol (path)"),
            ("relation_type", "subsidiary/joint_venture/associate filter"),
        ],
        "outputs": [
            ("subsidiary_id", "BIGINT", "Primary key"),
            ("parent_symbol", "VARCHAR(20)", "Parent company symbol"),
            ("subsidiary_name", "VARCHAR(255)", "Legal name of subsidiary"),
            ("cin", "CHAR(21)", "Subsidiary CIN"),
            ("relation_type", "VARCHAR(20)", "subsidiary/joint_venture/associate"),
            ("ownership_pct", "NUMERIC(7,4)", "Parent ownership percentage"),
            ("country", "VARCHAR(100)", "Country of incorporation"),
            ("business_activity", "VARCHAR(500)", "Primary business activity"),
            ("is_listed", "BOOLEAN", "Independently listed flag"),
            ("consolidated", "BOOLEAN", "Included in consolidated statements"),
            ("incorporation_date", "DATE", "Date of incorporation"),
            ("updated_at", "TIMESTAMPTZ", "Last update"),
        ],
    },
    {
        "num": 8, "name": "Registered Office", "url": "/v1/company/{symbol}/registered-office",
        "freq": "Annual", "update": "With profile refresh",
        "inputs": [("symbol", "NSE symbol (path)")],
        "outputs": [
            ("symbol", "VARCHAR(20)", "Company symbol"),
            ("address_line_1", "VARCHAR(255)", "First line of address"),
            ("address_line_2", "VARCHAR(255)", "Second line of address"),
            ("city", "VARCHAR(100)", "City"),
            ("state", "VARCHAR(100)", "State"),
            ("pincode", "VARCHAR(10)", "Postal code"),
            ("country", "VARCHAR(100)", "Country"),
            ("phone", "VARCHAR(50)", "Phone number"),
            ("fax", "VARCHAR(50)", "Fax number"),
            ("email", "VARCHAR(255)", "Contact email"),
            ("website", "VARCHAR(255)", "Website URL"),
            ("updated_at", "TIMESTAMPTZ", "Last update"),
        ],
    },
    {
        "num": 9, "name": "Registrar & Share Transfer Agent", "url": "/v1/company/{symbol}/rta",
        "freq": "Annual", "update": "With annual filings",
        "inputs": [("symbol", "NSE symbol (path)")],
        "outputs": [
            ("symbol", "VARCHAR(20)", "Company symbol"),
            ("rta_name", "VARCHAR(255)", "RTA name e.g. KFin Technologies"),
            ("rta_address", "TEXT", "RTA full address"),
            ("rta_phone", "VARCHAR(50)", "RTA contact number"),
            ("rta_email", "VARCHAR(255)", "RTA contact email"),
            ("rta_website", "VARCHAR(255)", "RTA website URL"),
            ("effective_from", "DATE", "Date this RTA was appointed"),
            ("updated_at", "TIMESTAMPTZ", "Last update"),
        ],
    },
    {
        "num": 10, "name": "Auditor Information", "url": "/v1/company/{symbol}/auditor",
        "freq": "Annual", "update": "With annual filings",
        "inputs": [("symbol", "NSE symbol (path)")],
        "outputs": [
            ("auditor_id", "BIGINT", "Primary key"),
            ("symbol", "VARCHAR(20)", "Company symbol"),
            ("auditor_name", "VARCHAR(255)", "Statutory auditor firm name"),
            ("firm_registration_no", "VARCHAR(50)", "ICAI firm registration number"),
            ("appointment_date", "DATE", "Date of appointment"),
            ("term_end_date", "DATE", "Date when current term ends"),
            ("audit_fee_lakh", "NUMERIC(12,2)", "Annual audit fee in INR lakhs"),
            ("is_current", "BOOLEAN", "Currently active auditor flag"),
            ("updated_at", "TIMESTAMPTZ", "Last update"),
        ],
    },
    {
        "num": 11, "name": "Live Quote NSE", "url": "/v1/quote/nse/{symbol}",
        "freq": "Real-time", "update": "Every 5 seconds during 09:15-15:30 IST",
        "inputs": [("symbol", "NSE symbol (path, required)")],
        "outputs": [
            ("symbol", "VARCHAR(20)", "NSE symbol"),
            ("company_name", "VARCHAR(255)", "Full company name"),
            ("ltp", "NUMERIC(14,4)", "Last traded price"),
            ("change", "NUMERIC(14,4)", "Absolute change vs previous close"),
            ("change_pct", "NUMERIC(10,4)", "Percentage change vs previous close"),
            ("open", "NUMERIC(14,4)", "Today opening price"),
            ("high", "NUMERIC(14,4)", "Day high price"),
            ("low", "NUMERIC(14,4)", "Day low price"),
            ("prev_close", "NUMERIC(14,4)", "Previous day closing price"),
            ("volume", "BIGINT", "Total traded quantity"),
            ("value_cr", "NUMERIC(18,4)", "Total traded value in INR crores"),
            ("vwap", "NUMERIC(14,4)", "Volume-weighted average price"),
            ("bid_price", "NUMERIC(14,4)", "Best buy price"),
            ("bid_qty", "INTEGER", "Best buy quantity"),
            ("ask_price", "NUMERIC(14,4)", "Best sell price"),
            ("ask_qty", "INTEGER", "Best sell quantity"),
            ("circuit_upper", "NUMERIC(14,4)", "Upper circuit limit"),
            ("circuit_lower", "NUMERIC(14,4)", "Lower circuit limit"),
            ("week52_high", "NUMERIC(14,4)", "52-week high price"),
            ("week52_low", "NUMERIC(14,4)", "52-week low price"),
            ("face_value", "NUMERIC(10,2)", "Face value per share"),
            ("exchange", "VARCHAR(5)", "Exchange code (NSE)"),
            ("last_trade_time_ist", "TIMESTAMP", "Last tick timestamp"),
            ("updated_at", "TIMESTAMPTZ", "Snapshot timestamp"),
        ],
    },
    {
        "num": 12, "name": "Live Quote BSE", "url": "/v1/quote/bse/{symbol}",
        "freq": "Real-time", "update": "Every 5 seconds during market hours",
        "inputs": [("symbol", "BSE code or symbol (path)")],
        "outputs": [
            ("symbol", "VARCHAR(20)", "BSE symbol"),
            ("bse_code", "INTEGER", "BSE numeric security code"),
            ("company_name", "VARCHAR(255)", "Company name"),
            ("ltp", "NUMERIC(14,4)", "Last traded price on BSE"),
            ("change_pct", "NUMERIC(10,4)", "Percentage change"),
            ("open", "NUMERIC(14,4)", "Opening price"),
            ("high", "NUMERIC(14,4)", "Day high"),
            ("low", "NUMERIC(14,4)", "Day low"),
            ("prev_close", "NUMERIC(14,4)", "Previous close"),
            ("volume", "BIGINT", "Traded quantity"),
            ("value_cr", "NUMERIC(18,4)", "Traded value in crores"),
            ("vwap", "NUMERIC(14,4)", "VWAP"),
            ("exchange", "VARCHAR(5)", "BSE"),
            ("updated_at", "TIMESTAMPTZ", "Snapshot timestamp"),
        ],
    },
    {
        "num": 13, "name": "Live Quote Combined", "url": "/v1/quote/{symbol}",
        "freq": "Real-time", "update": "Every 5 seconds during market hours",
        "inputs": [("symbol", "NSE symbol (path, required)")],
        "outputs": [
            ("symbol", "VARCHAR(20)", "NSE symbol"),
            ("nse_ltp", "NUMERIC(14,4)", "NSE last traded price"),
            ("bse_ltp", "NUMERIC(14,4)", "BSE last traded price"),
            ("spread_bps", "NUMERIC(10,4)", "NSE-BSE price spread in basis points"),
            ("preferred_exchange", "VARCHAR(5)", "Higher-volume exchange"),
            ("combined_volume", "BIGINT", "Total volume across both exchanges"),
            ("combined_value_cr", "NUMERIC(18,4)", "Combined traded value"),
            ("vwap_combined", "NUMERIC(14,4)", "Volume-weighted price across both"),
            ("change_pct_combined", "NUMERIC(10,4)", "Average change percentage"),
            ("timestamp_ist", "TIMESTAMP", "Snapshot time"),
        ],
    },
    {
        "num": 14, "name": "Intraday OHLC 1-minute", "url": "/v1/ohlc/intraday/{symbol}?interval=1m",
        "freq": "Real-time", "update": "New bar every minute during market hours",
        "inputs": [
            ("symbol", "NSE symbol (path)"),
            ("interval", "Bar interval (1m)"),
            ("from", "Start ISO datetime"),
            ("to", "End ISO datetime"),
        ],
        "outputs": [
            ("symbol", "VARCHAR(20)", "NSE symbol"),
            ("timestamp_ist", "TIMESTAMP", "Bar opening time"),
            ("open", "NUMERIC(14,4)", "Bar opening price"),
            ("high", "NUMERIC(14,4)", "Bar high"),
            ("low", "NUMERIC(14,4)", "Bar low"),
            ("close", "NUMERIC(14,4)", "Bar closing price"),
            ("volume", "BIGINT", "Volume in bar"),
            ("vwap", "NUMERIC(14,4)", "Volume-weighted average price for bar"),
            ("trade_count", "INTEGER", "Number of trades in bar"),
            ("interval", "VARCHAR(5)", "1m"),
        ],
    },
    {
        "num": 15, "name": "Intraday OHLC 5-minute", "url": "/v1/ohlc/intraday/{symbol}?interval=5m",
        "freq": "Real-time", "update": "New bar every 5 minutes during market hours",
        "inputs": [
            ("symbol", "NSE symbol (path)"),
            ("interval", "Bar interval (5m)"),
            ("from", "Start datetime"),
            ("to", "End datetime"),
        ],
        "outputs": [
            ("symbol", "VARCHAR(20)", "NSE symbol"),
            ("timestamp_ist", "TIMESTAMP", "Bar open time"),
            ("open", "NUMERIC(14,4)", "Open price"),
            ("high", "NUMERIC(14,4)", "High price"),
            ("low", "NUMERIC(14,4)", "Low price"),
            ("close", "NUMERIC(14,4)", "Close price"),
            ("volume", "BIGINT", "Volume"),
            ("vwap", "NUMERIC(14,4)", "VWAP"),
            ("trade_count", "INTEGER", "Trade count"),
            ("interval", "VARCHAR(5)", "5m"),
        ],
    },
    {
        "num": 16, "name": "Intraday OHLC 15-minute", "url": "/v1/ohlc/intraday/{symbol}?interval=15m",
        "freq": "Real-time", "update": "New bar every 15 minutes",
        "inputs": [
            ("symbol", "NSE symbol (path)"),
            ("interval", "15m"),
            ("from", "Start"),
            ("to", "End"),
        ],
        "outputs": [
            ("symbol", "VARCHAR(20)", "NSE symbol"),
            ("timestamp_ist", "TIMESTAMP", "Bar open time"),
            ("open", "NUMERIC(14,4)", "Open"),
            ("high", "NUMERIC(14,4)", "High"),
            ("low", "NUMERIC(14,4)", "Low"),
            ("close", "NUMERIC(14,4)", "Close"),
            ("volume", "BIGINT", "Volume"),
            ("vwap", "NUMERIC(14,4)", "VWAP"),
            ("trade_count", "INTEGER", "Trade count"),
            ("interval", "VARCHAR(5)", "15m"),
        ],
    },
    {
        "num": 17, "name": "Daily OHLC History", "url": "/v1/ohlc/daily/{symbol}",
        "freq": "EOD", "update": "18:00 IST daily",
        "inputs": [
            ("symbol", "NSE symbol (path)"),
            ("from", "Start date YYYY-MM-DD"),
            ("to", "End date YYYY-MM-DD"),
            ("adjusted", "Split/bonus adjusted (default false)"),
        ],
        "outputs": [
            ("symbol", "VARCHAR(20)", "NSE symbol"),
            ("trade_date", "DATE", "Trading date"),
            ("open", "NUMERIC(14,4)", "Opening price"),
            ("high", "NUMERIC(14,4)", "Day high"),
            ("low", "NUMERIC(14,4)", "Day low"),
            ("close", "NUMERIC(14,4)", "Closing price"),
            ("volume", "BIGINT", "Total traded quantity"),
            ("value_cr", "NUMERIC(18,4)", "Total traded value in crores"),
            ("delivery_qty", "BIGINT", "Quantity actually delivered"),
            ("delivery_pct", "NUMERIC(7,4)", "Delivery as percentage of total volume"),
            ("adjustment_factor", "NUMERIC(12,8)", "Cumulative split/bonus factor"),
            ("prev_close", "NUMERIC(14,4)", "Previous day close"),
            ("vwap", "NUMERIC(14,4)", "Volume-weighted average price"),
            ("trade_count", "INTEGER", "Number of trades"),
        ],
    },
    {
        "num": 18, "name": "Weekly OHLC", "url": "/v1/ohlc/weekly/{symbol}",
        "freq": "EOD (Friday)", "update": "Friday 18:45 IST",
        "inputs": [
            ("symbol", "NSE symbol (path)"),
            ("from", "Start date"),
            ("to", "End date"),
            ("adjusted", "Adjusted prices flag"),
        ],
        "outputs": [
            ("symbol", "VARCHAR(20)", "NSE symbol"),
            ("week_start_date", "DATE", "Week starting Monday"),
            ("week_end_date", "DATE", "Week ending Friday"),
            ("open", "NUMERIC(14,4)", "Week opening price"),
            ("high", "NUMERIC(14,4)", "Week high"),
            ("low", "NUMERIC(14,4)", "Week low"),
            ("close", "NUMERIC(14,4)", "Week closing price"),
            ("volume", "BIGINT", "Total weekly volume"),
            ("value_cr", "NUMERIC(18,4)", "Weekly traded value in crores"),
        ],
    },
    {
        "num": 19, "name": "Monthly OHLC", "url": "/v1/ohlc/monthly/{symbol}",
        "freq": "EOD (month-end)", "update": "Last trading day 19:00 IST",
        "inputs": [
            ("symbol", "NSE symbol (path)"),
            ("from", "Start month"),
            ("to", "End month"),
            ("adjusted", "Adjusted flag"),
        ],
        "outputs": [
            ("symbol", "VARCHAR(20)", "NSE symbol"),
            ("month_start_date", "DATE", "First trading day of month"),
            ("month_end_date", "DATE", "Last trading day of month"),
            ("open", "NUMERIC(14,4)", "Month opening price"),
            ("high", "NUMERIC(14,4)", "Month high"),
            ("low", "NUMERIC(14,4)", "Month low"),
            ("close", "NUMERIC(14,4)", "Month closing price"),
            ("volume", "BIGINT", "Monthly total volume"),
            ("value_cr", "NUMERIC(18,4)", "Monthly traded value in crores"),
        ],
    },
    {
        "num": 20, "name": "52-Week High/Low", "url": "/v1/52week/{symbol}",
        "freq": "EOD", "update": "18:35 IST",
        "inputs": [("symbol", "NSE symbol (path)")],
        "outputs": [
            ("symbol", "VARCHAR(20)", "NSE symbol"),
            ("high_52w", "NUMERIC(14,4)", "52-week high price"),
            ("high_52w_date", "DATE", "Date when 52w high was achieved"),
            ("low_52w", "NUMERIC(14,4)", "52-week low price"),
            ("low_52w_date", "DATE", "Date when 52w low was achieved"),
            ("current_to_high_pct", "NUMERIC(10,4)", "Distance from 52w high (%)"),
            ("current_to_low_pct", "NUMERIC(10,4)", "Distance from 52w low (%)"),
            ("updated_at", "TIMESTAMPTZ", "Last computation"),
        ],
    },
    {
        "num": 21, "name": "All-Time High/Low", "url": "/v1/ath/{symbol}",
        "freq": "EOD", "update": "18:40 IST",
        "inputs": [
            ("symbol", "NSE symbol (path)"),
            ("adjusted", "Use adjusted prices flag"),
        ],
        "outputs": [
            ("symbol", "VARCHAR(20)", "NSE symbol"),
            ("ath", "NUMERIC(14,4)", "All-time high price"),
            ("ath_date", "DATE", "Date of all-time high"),
            ("atl", "NUMERIC(14,4)", "All-time low price"),
            ("atl_date", "DATE", "Date of all-time low"),
            ("current_to_ath_pct", "NUMERIC(10,4)", "Distance from ATH"),
            ("current_to_atl_pct", "NUMERIC(10,4)", "Distance from ATL"),
            ("days_since_ath", "INTEGER", "Trading days since ATH"),
        ],
    },
    {
        "num": 22, "name": "Adjusted Price History", "url": "/v1/ohlc/adjusted/{symbol}",
        "freq": "EOD", "update": "18:50 IST",
        "inputs": [
            ("symbol", "NSE symbol"),
            ("from", "Start date"),
            ("to", "End date"),
        ],
        "outputs": [
            ("symbol", "VARCHAR(20)", "NSE symbol"),
            ("trade_date", "DATE", "Trade date"),
            ("open", "NUMERIC(14,4)", "Adjusted open"),
            ("high", "NUMERIC(14,4)", "Adjusted high"),
            ("low", "NUMERIC(14,4)", "Adjusted low"),
            ("close", "NUMERIC(14,4)", "Adjusted close"),
            ("volume", "BIGINT", "Adjusted volume"),
            ("adjustment_factor", "NUMERIC(12,8)", "Cumulative adjustment factor"),
            ("raw_close", "NUMERIC(14,4)", "Unadjusted close"),
        ],
    },
    {
        "num": 23, "name": "Tick Snapshot", "url": "/v1/tick/{symbol}",
        "freq": "Real-time", "update": "Every second during market hours",
        "inputs": [("symbol", "NSE symbol (path)")],
        "outputs": [
            ("symbol", "VARCHAR(20)", "NSE symbol"),
            ("timestamp_ist", "TIMESTAMP", "Tick timestamp"),
            ("ltp", "NUMERIC(14,4)", "Last traded price"),
            ("bids", "JSONB", "Array of 5 best bid {price, qty, orders}"),
            ("asks", "JSONB", "Array of 5 best ask {price, qty, orders}"),
            ("total_buy_qty", "BIGINT", "Total buy quantity across all bids"),
            ("total_sell_qty", "BIGINT", "Total sell quantity across all asks"),
        ],
    },
    {
        "num": 24, "name": "Pre-Open Session", "url": "/v1/pre-open",
        "freq": "Daily (09:00-09:08 IST)", "update": "Updated every 30s during pre-open",
        "inputs": [
            ("symbol", "Filter by symbol (optional)"),
            ("index", "Filter by index e.g. NIFTY50"),
        ],
        "outputs": [
            ("symbol", "VARCHAR(20)", "NSE symbol"),
            ("iep", "NUMERIC(14,4)", "Indicative Equilibrium Price"),
            ("change", "NUMERIC(14,4)", "Change vs previous close"),
            ("change_pct", "NUMERIC(10,4)", "Percentage change"),
            ("final_price", "NUMERIC(14,4)", "Final discovered price at 09:08"),
            ("final_qty", "BIGINT", "Matched quantity"),
            ("total_buy_qty", "BIGINT", "Total pre-open buy orders"),
            ("total_sell_qty", "BIGINT", "Total pre-open sell orders"),
            ("atc_buy_qty", "BIGINT", "At-cost buy quantity"),
            ("atc_sell_qty", "BIGINT", "At-cost sell quantity"),
            ("session_date", "DATE", "Trading session date"),
        ],
    },
    {
        "num": 25, "name": "Closing Settlement Price", "url": "/v1/closing/{symbol}",
        "freq": "EOD", "update": "16:00 IST",
        "inputs": [
            ("symbol", "NSE symbol"),
            ("from", "Start date"),
            ("to", "End date"),
        ],
        "outputs": [
            ("symbol", "VARCHAR(20)", "NSE symbol"),
            ("trade_date", "DATE", "Trade date"),
            ("settlement_price", "NUMERIC(14,4)", "Settlement price for derivatives"),
            ("close_price", "NUMERIC(14,4)", "Weighted average price of last 30 minutes"),
            ("weighted_avg_price", "NUMERIC(14,4)", "Day VWAP"),
            ("total_traded_value_cr", "NUMERIC(18,4)", "Day total value"),
        ],
    },
    {
        "num": 26, "name": "Index Master", "url": "/v1/indices",
        "freq": "Monthly", "update": "1st of month 02:30 IST",
        "inputs": [
            ("exchange", "NSE or BSE filter"),
            ("index_type", "broad/sectoral/thematic/strategy"),
        ],
        "outputs": [
            ("index_id", "INTEGER", "Primary key"),
            ("index_name", "VARCHAR(100)", "Display name e.g. NIFTY 50"),
            ("index_symbol", "VARCHAR(50)", "Index symbol code"),
            ("exchange", "VARCHAR(5)", "Listing exchange"),
            ("index_type", "VARCHAR(20)", "broad/sectoral/thematic/strategy"),
            ("base_date", "DATE", "Index inception date"),
            ("base_value", "NUMERIC(14,4)", "Base value at inception"),
            ("constituent_count", "SMALLINT", "Number of constituents"),
            ("calculation_methodology", "VARCHAR(100)", "free-float/equal-weight/etc"),
            ("rebalance_frequency", "VARCHAR(50)", "semi-annual/quarterly/etc"),
            ("last_rebalance_date", "DATE", "Last rebalancing date"),
            ("is_tradeable", "BOOLEAN", "Has F&O instruments flag"),
            ("updated_at", "TIMESTAMPTZ", "Last update"),
        ],
    },
    {
        "num": 27, "name": "Index Live Quote", "url": "/v1/index/{name}/quote",
        "freq": "Real-time", "update": "Every 5 seconds during market hours",
        "inputs": [("name", "Index name/symbol (path)")],
        "outputs": [
            ("index_name", "VARCHAR(100)", "Index name"),
            ("ltp", "NUMERIC(14,4)", "Current index value"),
            ("change", "NUMERIC(14,4)", "Absolute change"),
            ("change_pct", "NUMERIC(10,4)", "Percentage change"),
            ("open", "NUMERIC(14,4)", "Opening value"),
            ("high", "NUMERIC(14,4)", "Day high"),
            ("low", "NUMERIC(14,4)", "Day low"),
            ("prev_close", "NUMERIC(14,4)", "Previous close"),
            ("year_high", "NUMERIC(14,4)", "52-week high"),
            ("year_low", "NUMERIC(14,4)", "52-week low"),
            ("pe_ratio", "NUMERIC(8,2)", "Index price-earnings ratio"),
            ("pb_ratio", "NUMERIC(8,2)", "Index price-book ratio"),
            ("dividend_yield", "NUMERIC(7,4)", "Aggregate dividend yield"),
            ("advances", "INTEGER", "Number of advancing constituents"),
            ("declines", "INTEGER", "Number of declining constituents"),
            ("unchanged", "INTEGER", "Unchanged count"),
            ("total_traded_value_cr", "NUMERIC(18,4)", "Total value traded"),
            ("timestamp_ist", "TIMESTAMP", "Snapshot time"),
        ],
    },
    {
        "num": 28, "name": "Index OHLC History", "url": "/v1/index/{name}/ohlc",
        "freq": "EOD", "update": "18:00 IST daily",
        "inputs": [
            ("name", "Index name"),
            ("from", "Start date"),
            ("to", "End date"),
            ("interval", "daily/weekly/monthly"),
        ],
        "outputs": [
            ("index_name", "VARCHAR(100)", "Index identifier"),
            ("trade_date", "DATE", "Trading date"),
            ("open", "NUMERIC(14,4)", "Index open"),
            ("high", "NUMERIC(14,4)", "Index high"),
            ("low", "NUMERIC(14,4)", "Index low"),
            ("close", "NUMERIC(14,4)", "Index close"),
            ("volume", "BIGINT", "Total constituent volume"),
            ("value_cr", "NUMERIC(18,4)", "Total value"),
            ("turnover_cr", "NUMERIC(18,4)", "Total turnover"),
            ("pe_ratio", "NUMERIC(8,2)", "EOD P/E ratio"),
            ("pb_ratio", "NUMERIC(8,2)", "EOD P/B ratio"),
            ("dividend_yield", "NUMERIC(7,4)", "EOD dividend yield"),
        ],
    },
    {
        "num": 29, "name": "Index Constituents", "url": "/v1/index/{name}/constituents",
        "freq": "Monthly", "update": "Rebalance day +1, 02:30 IST",
        "inputs": [
            ("name", "Index name (path)"),
            ("as_of_date", "Snapshot date (optional)"),
        ],
        "outputs": [
            ("index_name", "VARCHAR(100)", "Index name"),
            ("symbol", "VARCHAR(20)", "Constituent symbol"),
            ("company_name", "VARCHAR(255)", "Company name"),
            ("weight_pct", "NUMERIC(8,4)", "Weight in index"),
            ("free_float_market_cap_cr", "NUMERIC(18,2)", "Free-float market cap"),
            ("effective_from", "DATE", "Start of inclusion"),
            ("effective_to", "DATE", "End of inclusion (null if current)"),
        ],
    },
    {
        "num": 30, "name": "Constituent Weights History", "url": "/v1/index/{name}/weights",
        "freq": "Monthly (rebalance)", "update": "Rebalance day",
        "inputs": [
            ("name", "Index name"),
            ("from", "Start date"),
            ("to", "End date"),
        ],
        "outputs": [
            ("index_name", "VARCHAR(100)", "Index name"),
            ("symbol", "VARCHAR(20)", "Constituent symbol"),
            ("weight_pct", "NUMERIC(8,4)", "Weight as of date"),
            ("effective_date", "DATE", "Date weight became effective"),
            ("market_cap_cr", "NUMERIC(18,2)", "Free-float market cap"),
        ],
    },
]
