"""Equity APIs 66-100 — ratios history, shareholding, technical, news, research."""

EQUITY_APIS_66_100 = [
    {
        "num": 66, "name": "Financial Ratios History", "url": "/v1/ratios/{symbol}/history",
        "freq": "Quarterly", "update": "After results release",
        "inputs": [
            ("symbol", "NSE symbol"),
            ("from_period", "Start quarter"),
            ("to_period", "End quarter"),
            ("metric", "Specific ratio name filter"),
        ],
        "outputs": [
            ("symbol", "VARCHAR(20)", "Symbol"),
            ("period", "VARCHAR(15)", "Quarter or FY"),
            ("period_end_date", "DATE", "Period end date"),
            ("pe_ratio", "NUMERIC(10,4)", "Historical P/E"),
            ("pb_ratio", "NUMERIC(10,4)", "Historical P/B"),
            ("ev_to_ebitda", "NUMERIC(10,4)", "Historical EV/EBITDA"),
            ("roe_pct", "NUMERIC(10,4)", "Historical ROE"),
            ("roce_pct", "NUMERIC(10,4)", "Historical ROCE"),
            ("debt_to_equity", "NUMERIC(10,4)", "Historical D/E"),
            ("eps_basic", "NUMERIC(12,4)", "EPS for period"),
            ("dividend_yield_pct", "NUMERIC(8,4)", "Yield for period"),
            ("net_profit_margin_pct", "NUMERIC(10,4)", "NPM for period"),
        ],
    },
    {
        "num": 67, "name": "Segment Reporting", "url": "/v1/financials/{symbol}/segments",
        "freq": "Quarterly", "update": "With quarterly results",
        "inputs": [
            ("symbol", "NSE symbol"),
            ("period", "Quarter"),
            ("segment_type", "business or geographic"),
        ],
        "outputs": [
            ("segment_id", "BIGINT", "Primary key"),
            ("symbol", "VARCHAR(20)", "Symbol"),
            ("period", "VARCHAR(15)", "Quarter"),
            ("period_end_date", "DATE", "Period end"),
            ("segment_name", "VARCHAR(200)", "Segment name"),
            ("segment_type", "VARCHAR(20)", "business or geographic"),
            ("revenue_cr", "NUMERIC(18,2)", "Segment revenue"),
            ("revenue_pct", "NUMERIC(8,4)", "Share of total revenue"),
            ("ebit_cr", "NUMERIC(18,2)", "Segment EBIT"),
            ("ebit_margin_pct", "NUMERIC(8,4)", "Segment EBIT margin"),
            ("capital_employed_cr", "NUMERIC(18,2)", "Capital employed in segment"),
            ("assets_cr", "NUMERIC(18,2)", "Segment assets"),
        ],
    },
    {
        "num": 68, "name": "Standalone vs Consolidated", "url": "/v1/financials/{symbol}/comparison",
        "freq": "Quarterly", "update": "With quarterly results",
        "inputs": [("symbol", "NSE symbol"), ("period", "Period quarter")],
        "outputs": [
            ("symbol", "VARCHAR(20)", "Symbol"),
            ("period", "VARCHAR(15)", "Quarter"),
            ("revenue_standalone_cr", "NUMERIC(18,2)", "Standalone revenue"),
            ("revenue_consolidated_cr", "NUMERIC(18,2)", "Consolidated revenue"),
            ("pat_standalone_cr", "NUMERIC(18,2)", "Standalone PAT"),
            ("pat_consolidated_cr", "NUMERIC(18,2)", "Consolidated PAT"),
            ("ebitda_standalone_cr", "NUMERIC(18,2)", "Standalone EBITDA"),
            ("ebitda_consolidated_cr", "NUMERIC(18,2)", "Consolidated EBITDA"),
            ("subsidiary_contribution_pct", "NUMERIC(8,4)", "% of consolidated revenue from subs"),
        ],
    },
    {
        "num": 69, "name": "EPS History", "url": "/v1/eps-history/{symbol}",
        "freq": "Quarterly", "update": "With quarterly results",
        "inputs": [("symbol", "Symbol"), ("from_period", "Start"), ("to_period", "End")],
        "outputs": [
            ("symbol", "VARCHAR(20)", "Symbol"),
            ("period", "VARCHAR(15)", "Quarter or FY"),
            ("period_end_date", "DATE", "Period end"),
            ("eps_basic", "NUMERIC(12,4)", "Basic EPS for period"),
            ("eps_diluted", "NUMERIC(12,4)", "Diluted EPS"),
            ("cash_eps", "NUMERIC(12,4)", "Cash EPS (PAT + Depreciation)"),
            ("eps_ttm", "NUMERIC(12,4)", "TTM EPS as of period end"),
            ("yoy_growth_pct", "NUMERIC(10,4)", "YoY EPS growth"),
            ("qoq_growth_pct", "NUMERIC(10,4)", "QoQ EPS growth"),
        ],
    },
    {
        "num": 70, "name": "Book Value History", "url": "/v1/book-value/{symbol}",
        "freq": "Quarterly", "update": "After results",
        "inputs": [("symbol", "Symbol"), ("from_period", "Start"), ("to_period", "End")],
        "outputs": [
            ("symbol", "VARCHAR(20)", "Symbol"),
            ("period", "VARCHAR(15)", "Quarter or FY"),
            ("period_end_date", "DATE", "Period end"),
            ("book_value_per_share", "NUMERIC(14,4)", "BV per share"),
            ("tangible_book_value_per_share", "NUMERIC(14,4)", "Tangible BV per share"),
            ("net_worth_cr", "NUMERIC(18,2)", "Net worth in crores"),
            ("yoy_growth_pct", "NUMERIC(10,4)", "YoY BV growth"),
        ],
    },
    {
        "num": 71, "name": "ROE/ROCE History", "url": "/v1/roe-roce/{symbol}",
        "freq": "Quarterly", "update": "After results",
        "inputs": [("symbol", "Symbol"), ("from_period", "Start"), ("to_period", "End")],
        "outputs": [
            ("symbol", "VARCHAR(20)", "Symbol"),
            ("period", "VARCHAR(15)", "Period"),
            ("period_end_date", "DATE", "Period end"),
            ("roe_pct", "NUMERIC(10,4)", "Return on Equity"),
            ("roce_pct", "NUMERIC(10,4)", "Return on Capital Employed"),
            ("roa_pct", "NUMERIC(10,4)", "Return on Assets"),
            ("roic_pct", "NUMERIC(10,4)", "Return on Invested Capital"),
            ("3y_avg_roe_pct", "NUMERIC(10,4)", "Trailing 3-year avg ROE"),
            ("5y_avg_roe_pct", "NUMERIC(10,4)", "Trailing 5-year avg ROE"),
        ],
    },
    {
        "num": 72, "name": "Market Cap History", "url": "/v1/market-cap-history/{symbol}",
        "freq": "EOD", "update": "18:35 IST",
        "inputs": [("symbol", "Symbol"), ("from_date", "Start"), ("to_date", "End")],
        "outputs": [
            ("symbol", "VARCHAR(20)", "Symbol"),
            ("trade_date", "DATE", "Trade date"),
            ("close_price", "NUMERIC(14,4)", "Closing price"),
            ("shares_outstanding", "BIGINT", "Total shares outstanding"),
            ("market_cap_cr", "NUMERIC(18,2)", "Total market cap"),
            ("free_float_market_cap_cr", "NUMERIC(18,2)", "Free-float market cap"),
            ("market_cap_category", "VARCHAR(20)", "Large/Mid/Small/Micro"),
        ],
    },
    {
        "num": 73, "name": "Historical PE/PB", "url": "/v1/historical-pe-pb/{symbol}",
        "freq": "EOD", "update": "18:40 IST",
        "inputs": [("symbol", "Symbol"), ("from_date", "Start"), ("to_date", "End")],
        "outputs": [
            ("symbol", "VARCHAR(20)", "Symbol"),
            ("trade_date", "DATE", "Trade date"),
            ("close_price", "NUMERIC(14,4)", "Close price"),
            ("eps_ttm", "NUMERIC(12,4)", "TTM EPS"),
            ("book_value_per_share", "NUMERIC(14,4)", "BV per share"),
            ("pe_ratio", "NUMERIC(10,4)", "P/E ratio"),
            ("pb_ratio", "NUMERIC(10,4)", "P/B ratio"),
            ("ev_to_ebitda", "NUMERIC(10,4)", "EV/EBITDA"),
            ("dividend_yield_pct", "NUMERIC(8,4)", "Dividend yield"),
        ],
    },
    {
        "num": 74, "name": "Shareholding Pattern", "url": "/v1/shareholding/{symbol}",
        "freq": "Quarterly", "update": "Within 21 days of quarter-end",
        "inputs": [
            ("symbol", "Symbol"),
            ("from_period", "Start"),
            ("to_period", "End"),
        ],
        "outputs": [
            ("sp_id", "BIGINT", "Primary key"),
            ("symbol", "VARCHAR(20)", "Symbol"),
            ("period", "VARCHAR(15)", "Quarter"),
            ("period_end_date", "DATE", "Period end"),
            ("promoter_holding_pct", "NUMERIC(8,4)", "Promoter holding %"),
            ("promoter_pledged_pct", "NUMERIC(8,4)", "Pledged % of promoter holding"),
            ("fii_holding_pct", "NUMERIC(8,4)", "FII total holding %"),
            ("dii_holding_pct", "NUMERIC(8,4)", "DII total holding %"),
            ("mf_holding_pct", "NUMERIC(8,4)", "Mutual fund holding %"),
            ("insurance_holding_pct", "NUMERIC(8,4)", "Insurance company holding %"),
            ("government_holding_pct", "NUMERIC(8,4)", "Government holding %"),
            ("retail_holding_pct", "NUMERIC(8,4)", "Retail individuals < ₹2L"),
            ("hni_holding_pct", "NUMERIC(8,4)", "HNI individuals > ₹2L"),
            ("bodies_corporate_pct", "NUMERIC(8,4)", "Body corporate holding"),
            ("others_pct", "NUMERIC(8,4)", "Other category holding"),
            ("total_shareholders", "INTEGER", "Total shareholder count"),
            ("shares_outstanding", "BIGINT", "Total shares outstanding"),
        ],
    },
    {
        "num": 75, "name": "Promoter Holdings Detail", "url": "/v1/shareholding/{symbol}/promoter",
        "freq": "Quarterly", "update": "With shareholding release",
        "inputs": [("symbol", "Symbol"), ("period", "Quarter")],
        "outputs": [
            ("id", "BIGINT", "Primary key"),
            ("symbol", "VARCHAR(20)", "Symbol"),
            ("period", "VARCHAR(15)", "Quarter"),
            ("promoter_name", "VARCHAR(255)", "Promoter entity name"),
            ("promoter_category", "VARCHAR(50)", "Individual/HUF/Body Corporate/Foreign"),
            ("shares_held", "BIGINT", "Shares held"),
            ("holding_pct", "NUMERIC(8,4)", "Holding percentage"),
            ("pledged_shares", "BIGINT", "Pledged shares"),
            ("pledged_pct", "NUMERIC(8,4)", "Pledged %"),
            ("encumbered_shares", "BIGINT", "Encumbered shares"),
            ("change_from_prev_period_pct", "NUMERIC(10,4)", "QoQ change in %"),
        ],
    },
    {
        "num": 76, "name": "Public Shareholding Breakdown", "url": "/v1/shareholding/{symbol}/public",
        "freq": "Quarterly", "update": "With shareholding release",
        "inputs": [("symbol", "Symbol"), ("period", "Quarter")],
        "outputs": [
            ("id", "BIGINT", "Primary key"),
            ("symbol", "VARCHAR(20)", "Symbol"),
            ("period", "VARCHAR(15)", "Quarter"),
            ("category", "VARCHAR(50)", "MF/FII/Insurance/Banks/NBFC/Retail/HNI/Trusts/NRI"),
            ("shares_held", "BIGINT", "Total shares in category"),
            ("holding_pct", "NUMERIC(8,4)", "% holding"),
            ("shareholder_count", "INTEGER", "Number of shareholders in category"),
        ],
    },
    {
        "num": 77, "name": "FII Holdings", "url": "/v1/shareholding/{symbol}/fii",
        "freq": "Quarterly", "update": "Within 30 days of quarter-end",
        "inputs": [("symbol", "Symbol"), ("from_period", "Start"), ("to_period", "End")],
        "outputs": [
            ("id", "BIGINT", "Primary key"),
            ("symbol", "VARCHAR(20)", "Symbol"),
            ("period", "VARCHAR(15)", "Quarter"),
            ("fii_name", "VARCHAR(255)", "FII entity name"),
            ("category", "VARCHAR(20)", "Cat I or Cat II"),
            ("shares_held", "BIGINT", "Shares held"),
            ("holding_pct", "NUMERIC(8,4)", "Holding %"),
            ("market_value_cr", "NUMERIC(18,2)", "Position value in crores"),
            ("change_from_prev_period_shares", "BIGINT", "QoQ change in shares"),
            ("change_from_prev_period_pct", "NUMERIC(10,4)", "QoQ % change"),
        ],
    },
    {
        "num": 78, "name": "DII Holdings", "url": "/v1/shareholding/{symbol}/dii",
        "freq": "Quarterly", "update": "Within 30 days of quarter-end",
        "inputs": [("symbol", "Symbol"), ("from_period", "Start"), ("to_period", "End")],
        "outputs": [
            ("id", "BIGINT", "Primary key"),
            ("symbol", "VARCHAR(20)", "Symbol"),
            ("period", "VARCHAR(15)", "Quarter"),
            ("dii_name", "VARCHAR(255)", "DII entity name"),
            ("dii_category", "VARCHAR(50)", "MF/Insurance/Bank/NBFC/Pension"),
            ("shares_held", "BIGINT", "Shares held"),
            ("holding_pct", "NUMERIC(8,4)", "Holding %"),
            ("market_value_cr", "NUMERIC(18,2)", "Position value"),
            ("change_from_prev_period_pct", "NUMERIC(10,4)", "QoQ change %"),
        ],
    },
    {
        "num": 79, "name": "Mutual Fund Holdings in Stock", "url": "/v1/shareholding/{symbol}/mf-holdings",
        "freq": "Monthly", "update": "7th of month",
        "inputs": [
            ("symbol", "Symbol (path)"),
            ("as_of_month", "Month YYYY-MM"),
            ("top_n", "Top N schemes (default 50)"),
        ],
        "outputs": [
            ("id", "BIGINT", "Primary key"),
            ("symbol", "VARCHAR(20)", "Symbol"),
            ("as_of_month", "DATE", "Snapshot month"),
            ("scheme_code", "VARCHAR(20)", "AMFI scheme code"),
            ("scheme_name", "VARCHAR(255)", "Scheme name"),
            ("amc_name", "VARCHAR(255)", "AMC name"),
            ("shares_held", "BIGINT", "Shares held by scheme"),
            ("holding_pct_of_scheme", "NUMERIC(8,4)", "Weight in scheme"),
            ("holding_pct_of_stock", "NUMERIC(8,4)", "Holding as % of total equity"),
            ("market_value_cr", "NUMERIC(18,2)", "Position value"),
            ("month_over_month_change_shares", "BIGINT", "MoM share change"),
            ("is_new_addition", "BOOLEAN", "New scheme entry flag"),
            ("is_complete_exit", "BOOLEAN", "Complete exit flag"),
        ],
    },
    {
        "num": 80, "name": "Peer Comparison", "url": "/v1/peer-comparison/{symbol}",
        "freq": "Daily", "update": "18:50 IST",
        "inputs": [
            ("symbol", "Base symbol"),
            ("peer_count", "Number of peers (default 5)"),
        ],
        "outputs": [
            ("base_symbol", "VARCHAR(20)", "Base company"),
            ("peer_symbol", "VARCHAR(20)", "Peer company"),
            ("peer_name", "VARCHAR(255)", "Peer company name"),
            ("sector", "VARCHAR(100)", "Common sector"),
            ("market_cap_cr", "NUMERIC(18,2)", "Peer market cap"),
            ("pe_ratio", "NUMERIC(10,4)", "Peer P/E"),
            ("pb_ratio", "NUMERIC(10,4)", "Peer P/B"),
            ("roe_pct", "NUMERIC(10,4)", "Peer ROE"),
            ("revenue_ttm_cr", "NUMERIC(18,2)", "TTM revenue"),
            ("pat_ttm_cr", "NUMERIC(18,2)", "TTM PAT"),
            ("debt_to_equity", "NUMERIC(10,4)", "D/E ratio"),
            ("dividend_yield_pct", "NUMERIC(8,4)", "Dividend yield"),
            ("similarity_score", "NUMERIC(5,4)", "Similarity score 0-1"),
        ],
    },
    {
        "num": 81, "name": "Delivery Percentage", "url": "/v1/delivery/{symbol}",
        "freq": "EOD", "update": "19:00 IST",
        "inputs": [("symbol", "Symbol"), ("from_date", "Start"), ("to_date", "End")],
        "outputs": [
            ("symbol", "VARCHAR(20)", "Symbol"),
            ("trade_date", "DATE", "Trade date"),
            ("total_volume", "BIGINT", "Total traded quantity"),
            ("delivery_qty", "BIGINT", "Delivery quantity"),
            ("delivery_pct", "NUMERIC(7,4)", "Delivery as % of volume"),
            ("traded_value_cr", "NUMERIC(18,4)", "Total value"),
            ("delivery_value_cr", "NUMERIC(18,4)", "Delivery value"),
            ("delivery_pct_avg_30d", "NUMERIC(7,4)", "30-day rolling avg delivery %"),
        ],
    },
    {
        "num": 82, "name": "Volume Analysis", "url": "/v1/volume-analysis/{symbol}",
        "freq": "EOD", "update": "19:00 IST",
        "inputs": [("symbol", "Symbol"), ("from_date", "Start"), ("to_date", "End")],
        "outputs": [
            ("symbol", "VARCHAR(20)", "Symbol"),
            ("trade_date", "DATE", "Trade date"),
            ("volume", "BIGINT", "Day volume"),
            ("avg_volume_5d", "BIGINT", "5-day avg volume"),
            ("avg_volume_30d", "BIGINT", "30-day avg volume"),
            ("avg_volume_90d", "BIGINT", "90-day avg volume"),
            ("volume_ratio_to_avg30d", "NUMERIC(10,4)", "Volume vs 30d avg ratio"),
            ("is_volume_spike", "BOOLEAN", "Volume > 2x of 30d avg"),
            ("value_cr", "NUMERIC(18,4)", "Day traded value"),
            ("vwap", "NUMERIC(14,4)", "Day VWAP"),
        ],
    },
    {
        "num": 83, "name": "Moving Averages", "url": "/v1/ma/{symbol}",
        "freq": "EOD", "update": "18:45 IST",
        "inputs": [("symbol", "Symbol"), ("as_of_date", "Date (optional, default latest)")],
        "outputs": [
            ("symbol", "VARCHAR(20)", "Symbol"),
            ("as_of_date", "DATE", "Reference date"),
            ("close_price", "NUMERIC(14,4)", "Close price"),
            ("sma_5", "NUMERIC(14,4)", "5-day Simple MA"),
            ("sma_10", "NUMERIC(14,4)", "10-day Simple MA"),
            ("sma_20", "NUMERIC(14,4)", "20-day Simple MA"),
            ("sma_50", "NUMERIC(14,4)", "50-day Simple MA"),
            ("sma_100", "NUMERIC(14,4)", "100-day Simple MA"),
            ("sma_200", "NUMERIC(14,4)", "200-day Simple MA"),
            ("ema_9", "NUMERIC(14,4)", "9-day Exponential MA"),
            ("ema_21", "NUMERIC(14,4)", "21-day Exponential MA"),
            ("ema_50", "NUMERIC(14,4)", "50-day Exponential MA"),
            ("ema_200", "NUMERIC(14,4)", "200-day Exponential MA"),
            ("price_above_sma200", "BOOLEAN", "Bullish trend flag"),
            ("golden_cross_active", "BOOLEAN", "SMA50 above SMA200"),
        ],
    },
    {
        "num": 84, "name": "RSI / MACD / Bollinger", "url": "/v1/technicals/{symbol}",
        "freq": "EOD", "update": "18:50 IST",
        "inputs": [("symbol", "Symbol"), ("as_of_date", "Reference date")],
        "outputs": [
            ("symbol", "VARCHAR(20)", "Symbol"),
            ("as_of_date", "DATE", "Reference date"),
            ("rsi_14", "NUMERIC(8,4)", "14-day Relative Strength Index"),
            ("rsi_signal", "VARCHAR(20)", "Overbought/Neutral/Oversold"),
            ("macd_line", "NUMERIC(12,4)", "MACD line (12 EMA - 26 EMA)"),
            ("macd_signal_line", "NUMERIC(12,4)", "9-day EMA of MACD"),
            ("macd_histogram", "NUMERIC(12,4)", "MACD minus signal"),
            ("macd_crossover", "VARCHAR(20)", "Bullish/Bearish/None"),
            ("bollinger_upper", "NUMERIC(14,4)", "Bollinger upper band (20,2)"),
            ("bollinger_middle", "NUMERIC(14,4)", "Bollinger middle (20-SMA)"),
            ("bollinger_lower", "NUMERIC(14,4)", "Bollinger lower band"),
            ("bollinger_pct_b", "NUMERIC(8,4)", "%B indicator"),
            ("bollinger_bandwidth", "NUMERIC(8,4)", "Band width %"),
            ("stochastic_k", "NUMERIC(8,4)", "Stochastic %K"),
            ("stochastic_d", "NUMERIC(8,4)", "Stochastic %D"),
            ("adx_14", "NUMERIC(8,4)", "14-day ADX"),
            ("atr_14", "NUMERIC(10,4)", "14-day Average True Range"),
        ],
    },
    {
        "num": 85, "name": "Beta History", "url": "/v1/beta/{symbol}",
        "freq": "EOD", "update": "19:00 IST",
        "inputs": [
            ("symbol", "Symbol"),
            ("benchmark", "Benchmark index (default Nifty 50)"),
            ("lookback_days", "Lookback window (default 252)"),
            ("from_date", "Start"),
            ("to_date", "End"),
        ],
        "outputs": [
            ("symbol", "VARCHAR(20)", "Symbol"),
            ("benchmark", "VARCHAR(50)", "Benchmark index"),
            ("as_of_date", "DATE", "Calculation date"),
            ("beta", "NUMERIC(8,4)", "Beta vs benchmark"),
            ("correlation", "NUMERIC(6,4)", "Correlation coefficient"),
            ("r_squared", "NUMERIC(6,4)", "R-squared"),
            ("alpha_annualized_pct", "NUMERIC(10,4)", "Annualized alpha"),
            ("lookback_days", "INTEGER", "Window used"),
        ],
    },
    {
        "num": 86, "name": "Volatility History", "url": "/v1/volatility/{symbol}",
        "freq": "EOD", "update": "19:00 IST",
        "inputs": [
            ("symbol", "Symbol"),
            ("from_date", "Start"),
            ("to_date", "End"),
        ],
        "outputs": [
            ("symbol", "VARCHAR(20)", "Symbol"),
            ("as_of_date", "DATE", "Date"),
            ("daily_return_pct", "NUMERIC(10,4)", "Daily return"),
            ("realized_vol_30d_pct", "NUMERIC(10,4)", "30-day realized volatility (annualized)"),
            ("realized_vol_90d_pct", "NUMERIC(10,4)", "90-day realized volatility"),
            ("realized_vol_1y_pct", "NUMERIC(10,4)", "1-year realized volatility"),
            ("downside_deviation_pct", "NUMERIC(10,4)", "Downside deviation"),
            ("max_drawdown_1y_pct", "NUMERIC(10,4)", "1-year max drawdown"),
            ("implied_vol_atm_pct", "NUMERIC(10,4)", "ATM option implied volatility"),
        ],
    },
    {
        "num": 87, "name": "Support/Resistance Levels", "url": "/v1/support-resistance/{symbol}",
        "freq": "EOD", "update": "19:10 IST",
        "inputs": [
            ("symbol", "Symbol"),
            ("lookback_days", "Window for swing detection"),
        ],
        "outputs": [
            ("symbol", "VARCHAR(20)", "Symbol"),
            ("as_of_date", "DATE", "Calculation date"),
            ("close_price", "NUMERIC(14,4)", "Reference close"),
            ("pivot_point", "NUMERIC(14,4)", "Pivot (H+L+C)/3"),
            ("resistance_1", "NUMERIC(14,4)", "R1"),
            ("resistance_2", "NUMERIC(14,4)", "R2"),
            ("resistance_3", "NUMERIC(14,4)", "R3"),
            ("support_1", "NUMERIC(14,4)", "S1"),
            ("support_2", "NUMERIC(14,4)", "S2"),
            ("support_3", "NUMERIC(14,4)", "S3"),
            ("fibonacci_levels", "JSONB", "Fibonacci retracements {0.236, 0.382, 0.5, 0.618, 0.786}"),
            ("swing_high", "NUMERIC(14,4)", "Recent swing high"),
            ("swing_low", "NUMERIC(14,4)", "Recent swing low"),
        ],
    },
    {
        "num": 88, "name": "Earnings Calendar", "url": "/v1/earnings-calendar",
        "freq": "Daily", "update": "22:30 IST",
        "inputs": [
            ("from_date", "Start date"),
            ("to_date", "End date"),
            ("symbol", "Symbol filter"),
            ("sector", "Sector filter"),
        ],
        "outputs": [
            ("event_id", "BIGINT", "Primary key"),
            ("symbol", "VARCHAR(20)", "Symbol"),
            ("company_name", "VARCHAR(255)", "Company name"),
            ("event_date", "DATE", "Expected results date"),
            ("quarter", "VARCHAR(15)", "Quarter being reported"),
            ("estimate_eps", "NUMERIC(12,4)", "Consensus EPS estimate"),
            ("estimate_revenue_cr", "NUMERIC(18,2)", "Consensus revenue estimate"),
            ("prior_period_eps", "NUMERIC(12,4)", "Previous comparable period EPS"),
            ("prior_period_revenue_cr", "NUMERIC(18,2)", "Previous comparable revenue"),
            ("analyst_count", "INTEGER", "Estimating analyst count"),
        ],
    },
    {
        "num": 89, "name": "Company News", "url": "/v1/news/{symbol}",
        "freq": "10-min", "update": "Every 10 minutes 24/7",
        "inputs": [
            ("symbol", "Symbol (path, optional for market-wide)"),
            ("from_datetime", "Start"),
            ("to_datetime", "End"),
            ("category", "results/management/regulatory/m_a/general"),
            ("sentiment", "positive/neutral/negative"),
            ("min_relevance_score", "Filter floor (default 0.5)"),
            ("page,limit", "Pagination"),
        ],
        "outputs": [
            ("news_id", "BIGINT", "Primary key"),
            ("symbol", "VARCHAR(20)", "Symbol"),
            ("headline", "VARCHAR(500)", "News headline"),
            ("summary", "TEXT", "Auto-generated summary"),
            ("body", "TEXT", "Full article body"),
            ("source", "VARCHAR(50)", "Source domain"),
            ("published_at_ist", "TIMESTAMP", "Publication time"),
            ("url", "VARCHAR(1000)", "Source URL"),
            ("url_hash", "CHAR(64)", "SHA256 of URL for dedup"),
            ("category", "VARCHAR(50)", "News category"),
            ("sentiment", "VARCHAR(20)", "positive/neutral/negative"),
            ("sentiment_score", "NUMERIC(6,4)", "Score from -1 to +1"),
            ("relevance_score", "NUMERIC(6,4)", "Symbol relevance 0-1"),
            ("tags", "TEXT[]", "Topic tags"),
        ],
    },
    {
        "num": 90, "name": "News Archive", "url": "/v1/news/archive",
        "freq": "EOD", "update": "23:00 IST",
        "inputs": [
            ("symbol", "Symbol filter"),
            ("from_datetime", "Start"),
            ("to_datetime", "End"),
            ("category", "Filter"),
            ("sentiment", "Filter"),
            ("page,limit", "Pagination"),
        ],
        "outputs": [
            ("news_id", "BIGINT", "Primary key"),
            ("symbol", "VARCHAR(20)", "Symbol"),
            ("headline", "VARCHAR(500)", "Headline"),
            ("summary", "TEXT", "Summary"),
            ("source", "VARCHAR(50)", "Source"),
            ("published_at_ist", "TIMESTAMP", "Publication time"),
            ("url", "VARCHAR(1000)", "URL"),
            ("category", "VARCHAR(50)", "Category"),
            ("sentiment", "VARCHAR(20)", "Sentiment"),
            ("sentiment_score", "NUMERIC(6,4)", "Score"),
            ("relevance_score", "NUMERIC(6,4)", "Relevance"),
        ],
    },
    {
        "num": 91, "name": "Brokerage Recommendations", "url": "/v1/research/{symbol}/recommendations",
        "freq": "Daily", "update": "18:00 IST",
        "inputs": [
            ("symbol", "Symbol (path)"),
            ("from_date", "Start"),
            ("to_date", "End"),
            ("broker", "Broker name filter"),
            ("rating", "BUY/SELL/HOLD/ADD/REDUCE"),
        ],
        "outputs": [
            ("rec_id", "BIGINT", "Primary key"),
            ("symbol", "VARCHAR(20)", "Symbol"),
            ("broker_name", "VARCHAR(255)", "Brokerage firm"),
            ("analyst_name", "VARCHAR(255)", "Analyst name"),
            ("rating", "VARCHAR(20)", "BUY/SELL/HOLD/ADD/REDUCE/NEUTRAL"),
            ("target_price", "NUMERIC(14,4)", "Target price INR"),
            ("previous_target_price", "NUMERIC(14,4)", "Prior target price"),
            ("target_change_pct", "NUMERIC(10,4)", "Target change %"),
            ("current_price_at_rec", "NUMERIC(14,4)", "Price at recommendation"),
            ("upside_pct", "NUMERIC(10,4)", "Implied upside %"),
            ("recommendation_date", "DATE", "Recommendation date"),
            ("report_url", "VARCHAR(1000)", "Source report URL"),
            ("summary", "TEXT", "Recommendation rationale"),
        ],
    },
    {
        "num": 92, "name": "Target Price Consensus", "url": "/v1/research/{symbol}/target",
        "freq": "Daily", "update": "18:30 IST",
        "inputs": [("symbol", "Symbol (path)")],
        "outputs": [
            ("symbol", "VARCHAR(20)", "Symbol"),
            ("as_of_date", "DATE", "Snapshot date"),
            ("consensus_rating", "VARCHAR(20)", "Strong Buy/Buy/Hold/Sell/Strong Sell"),
            ("consensus_target_price", "NUMERIC(14,4)", "Mean target price"),
            ("target_price_high", "NUMERIC(14,4)", "Highest target"),
            ("target_price_low", "NUMERIC(14,4)", "Lowest target"),
            ("target_price_median", "NUMERIC(14,4)", "Median target"),
            ("analyst_count", "INTEGER", "Number of analysts"),
            ("buy_count", "INTEGER", "Buy ratings count"),
            ("hold_count", "INTEGER", "Hold ratings count"),
            ("sell_count", "INTEGER", "Sell ratings count"),
            ("upside_to_consensus_pct", "NUMERIC(10,4)", "Upside vs current price"),
            ("last_30d_target_change_pct", "NUMERIC(10,4)", "Target change over 30d"),
        ],
    },
    {
        "num": 93, "name": "Analyst Coverage", "url": "/v1/research/{symbol}/coverage",
        "freq": "Daily", "update": "18:30 IST",
        "inputs": [("symbol", "Symbol (path)")],
        "outputs": [
            ("symbol", "VARCHAR(20)", "Symbol"),
            ("analyst_count_total", "INTEGER", "Total covering analysts"),
            ("analyst_count_active_90d", "INTEGER", "Active in last 90 days"),
            ("brokers", "JSONB", "Array of {broker, rating, target, date}"),
            ("coverage_started_date", "DATE", "Earliest coverage date"),
            ("avg_recommendation_score", "NUMERIC(5,4)", "Aggregate rec score 1-5"),
        ],
    },
    {
        "num": 94, "name": "Corporate Events Calendar", "url": "/v1/corporate-events",
        "freq": "Daily", "update": "22:30 IST",
        "inputs": [
            ("from_date", "Start"),
            ("to_date", "End"),
            ("event_type", "results/dividend/agm/buyback/board/ipo/etc"),
            ("symbol", "Symbol filter"),
        ],
        "outputs": [
            ("event_id", "BIGINT", "Primary key"),
            ("symbol", "VARCHAR(20)", "Symbol"),
            ("company_name", "VARCHAR(255)", "Company name"),
            ("event_type", "VARCHAR(50)", "Event category"),
            ("event_date", "DATE", "Scheduled event date"),
            ("description", "TEXT", "Event description"),
            ("source", "VARCHAR(50)", "Source feed"),
            ("is_price_sensitive", "BOOLEAN", "Material event flag"),
        ],
    },
    {
        "num": 95, "name": "Price Adjustment History", "url": "/v1/price-adjustments/{symbol}",
        "freq": "EOD", "update": "22:00 IST when applicable",
        "inputs": [("symbol", "Symbol"), ("from_date", "Start"), ("to_date", "End")],
        "outputs": [
            ("adj_id", "BIGINT", "Primary key"),
            ("symbol", "VARCHAR(20)", "Symbol"),
            ("ex_date", "DATE", "Ex-date applying adjustment"),
            ("adjustment_type", "VARCHAR(30)", "split/bonus/dividend/rights"),
            ("adjustment_factor", "NUMERIC(12,8)", "Multiplier applied to historical prices"),
            ("ratio", "VARCHAR(20)", "Action ratio if applicable"),
            ("dividend_amount", "NUMERIC(10,4)", "Dividend amount if applicable"),
            ("cumulative_adjustment_factor", "NUMERIC(12,8)", "Cumulative factor from inception"),
            ("notes", "TEXT", "Operational notes"),
        ],
    },
]
