"""Equity APIs 31-65 — market stats, corporate actions, F&O, deals, insider."""

EQUITY_APIS_31_65 = [
    {
        "num": 31, "name": "Top Gainers", "url": "/v1/top-gainers",
        "freq": "Real-time", "update": "Every 5 minutes during market hours",
        "inputs": [
            ("index", "Filter by index (NIFTY50/NIFTYBANK/NIFTYNEXT50)"),
            ("limit", "Number of results (default 10)"),
            ("series", "EQ/BE series filter"),
        ],
        "outputs": [
            ("rank", "INTEGER", "Rank by % gain"),
            ("symbol", "VARCHAR(20)", "NSE symbol"),
            ("company_name", "VARCHAR(255)", "Company name"),
            ("ltp", "NUMERIC(14,4)", "Last traded price"),
            ("change", "NUMERIC(14,4)", "Absolute change"),
            ("change_pct", "NUMERIC(10,4)", "Percentage gain"),
            ("volume", "BIGINT", "Traded volume"),
            ("value_cr", "NUMERIC(18,4)", "Traded value in crores"),
            ("index", "VARCHAR(50)", "Index context"),
            ("timestamp_ist", "TIMESTAMP", "Snapshot time"),
        ],
    },
    {
        "num": 32, "name": "Top Losers", "url": "/v1/top-losers",
        "freq": "Real-time", "update": "Every 5 minutes",
        "inputs": [
            ("index", "Index filter"),
            ("limit", "Result count"),
            ("series", "Series filter"),
        ],
        "outputs": [
            ("rank", "INTEGER", "Rank by % loss"),
            ("symbol", "VARCHAR(20)", "NSE symbol"),
            ("company_name", "VARCHAR(255)", "Company name"),
            ("ltp", "NUMERIC(14,4)", "Last price"),
            ("change", "NUMERIC(14,4)", "Absolute change"),
            ("change_pct", "NUMERIC(10,4)", "Percentage loss"),
            ("volume", "BIGINT", "Volume"),
            ("value_cr", "NUMERIC(18,4)", "Value in crores"),
            ("index", "VARCHAR(50)", "Index context"),
            ("timestamp_ist", "TIMESTAMP", "Snapshot time"),
        ],
    },
    {
        "num": 33, "name": "Most Active by Volume", "url": "/v1/most-active/volume",
        "freq": "Real-time", "update": "Every 5 minutes",
        "inputs": [("index", "Index filter"), ("limit", "Result count")],
        "outputs": [
            ("rank", "INTEGER", "Rank by volume"),
            ("symbol", "VARCHAR(20)", "NSE symbol"),
            ("company_name", "VARCHAR(255)", "Company name"),
            ("ltp", "NUMERIC(14,4)", "Last price"),
            ("change_pct", "NUMERIC(10,4)", "Day change %"),
            ("volume", "BIGINT", "Traded volume"),
            ("value_cr", "NUMERIC(18,4)", "Value in crores"),
            ("timestamp_ist", "TIMESTAMP", "Snapshot time"),
        ],
    },
    {
        "num": 34, "name": "Most Active by Value", "url": "/v1/most-active/value",
        "freq": "Real-time", "update": "Every 5 minutes",
        "inputs": [("index", "Index filter"), ("limit", "Count")],
        "outputs": [
            ("rank", "INTEGER", "Rank by value"),
            ("symbol", "VARCHAR(20)", "NSE symbol"),
            ("company_name", "VARCHAR(255)", "Company name"),
            ("ltp", "NUMERIC(14,4)", "Last price"),
            ("change_pct", "NUMERIC(10,4)", "Day change %"),
            ("volume", "BIGINT", "Volume"),
            ("value_cr", "NUMERIC(18,4)", "Value in crores (sort key)"),
            ("timestamp_ist", "TIMESTAMP", "Snapshot time"),
        ],
    },
    {
        "num": 35, "name": "Market Breadth", "url": "/v1/market-breadth",
        "freq": "Real-time", "update": "Every 5 minutes",
        "inputs": [
            ("exchange", "NSE or BSE (default NSE)"),
            ("index", "Index scope filter"),
        ],
        "outputs": [
            ("exchange", "VARCHAR(5)", "Exchange code"),
            ("index", "VARCHAR(50)", "Index scope"),
            ("advances", "INTEGER", "Number of advancing stocks"),
            ("declines", "INTEGER", "Number of declining stocks"),
            ("unchanged", "INTEGER", "Unchanged count"),
            ("advance_decline_ratio", "NUMERIC(8,4)", "A/D ratio"),
            ("high_52w_count", "INTEGER", "Stocks at 52w high"),
            ("low_52w_count", "INTEGER", "Stocks at 52w low"),
            ("upper_circuit_count", "INTEGER", "Stocks hitting upper circuit"),
            ("lower_circuit_count", "INTEGER", "Stocks hitting lower circuit"),
            ("total_traded", "INTEGER", "Total stocks traded"),
            ("timestamp_ist", "TIMESTAMP", "Snapshot time"),
        ],
    },
    {
        "num": 36, "name": "Corporate Actions (All)", "url": "/v1/corporate-actions",
        "freq": "EOD", "update": "22:00 IST",
        "inputs": [
            ("symbol", "Filter by symbol"),
            ("action_type", "DIVIDEND/BONUS/SPLIT/RIGHTS/BUYBACK/MERGER/DEMERGER/NAME_CHANGE"),
            ("from_date", "Start date"),
            ("to_date", "End date"),
        ],
        "outputs": [
            ("action_id", "BIGINT", "Primary key"),
            ("symbol", "VARCHAR(20)", "Company symbol"),
            ("action_type", "VARCHAR(30)", "Type of corporate action"),
            ("announcement_date", "DATE", "Date announced"),
            ("record_date", "DATE", "Record date for entitlement"),
            ("ex_date", "DATE", "Ex-date (trading without entitlement)"),
            ("payment_date", "DATE", "Payment/distribution date"),
            ("description", "TEXT", "Full description"),
            ("ratio", "VARCHAR(20)", "Ratio e.g. 1:1, 5:1"),
            ("dividend_per_share", "NUMERIC(10,4)", "Dividend amount per share"),
            ("dividend_type", "VARCHAR(20)", "Interim/Final/Special"),
            ("face_value_old", "NUMERIC(10,2)", "Old face value (for splits)"),
            ("face_value_new", "NUMERIC(10,2)", "New face value"),
            ("rights_price", "NUMERIC(14,4)", "Rights issue price"),
            ("buyback_price", "NUMERIC(14,4)", "Buyback offer price"),
            ("buyback_size_cr", "NUMERIC(14,2)", "Buyback size in crores"),
            ("purpose", "TEXT", "Stated purpose of action"),
            ("updated_at", "TIMESTAMPTZ", "Last update"),
        ],
    },
    {
        "num": 37, "name": "Dividend History", "url": "/v1/dividends/{symbol}",
        "freq": "EOD", "update": "22:05 IST",
        "inputs": [
            ("symbol", "NSE symbol"),
            ("from_date", "Start date"),
            ("to_date", "End date"),
        ],
        "outputs": [
            ("dividend_id", "BIGINT", "Primary key"),
            ("symbol", "VARCHAR(20)", "Symbol"),
            ("announcement_date", "DATE", "Announcement date"),
            ("ex_date", "DATE", "Ex-dividend date"),
            ("record_date", "DATE", "Record date"),
            ("payment_date", "DATE", "Payment date"),
            ("dividend_type", "VARCHAR(20)", "Interim/Final/Special/DRIP"),
            ("dividend_per_share", "NUMERIC(10,4)", "Amount per share"),
            ("face_value", "NUMERIC(10,2)", "Face value reference"),
            ("dividend_yield_at_announcement_pct", "NUMERIC(8,4)", "Yield at announcement"),
            ("total_payout_cr", "NUMERIC(14,2)", "Total dividend payout in crores"),
            ("currency", "VARCHAR(5)", "INR default"),
        ],
    },
    {
        "num": 38, "name": "Bonus Issues", "url": "/v1/bonus/{symbol}",
        "freq": "EOD", "update": "22:05 IST",
        "inputs": [("symbol", "NSE symbol"), ("from_date", "Start"), ("to_date", "End")],
        "outputs": [
            ("bonus_id", "BIGINT", "Primary key"),
            ("symbol", "VARCHAR(20)", "Symbol"),
            ("announcement_date", "DATE", "Announcement date"),
            ("ex_date", "DATE", "Ex-bonus date"),
            ("record_date", "DATE", "Record date"),
            ("ratio", "VARCHAR(20)", "Bonus ratio e.g. 1:1"),
            ("ratio_decimal", "NUMERIC(10,6)", "Ratio as decimal multiplier"),
            ("face_value", "NUMERIC(10,2)", "Face value reference"),
        ],
    },
    {
        "num": 39, "name": "Stock Splits", "url": "/v1/splits/{symbol}",
        "freq": "EOD", "update": "22:05 IST",
        "inputs": [("symbol", "NSE symbol"), ("from_date", "Start"), ("to_date", "End")],
        "outputs": [
            ("split_id", "BIGINT", "Primary key"),
            ("symbol", "VARCHAR(20)", "Symbol"),
            ("announcement_date", "DATE", "Announcement date"),
            ("ex_date", "DATE", "Ex-split date"),
            ("record_date", "DATE", "Record date"),
            ("old_face_value", "NUMERIC(10,2)", "Pre-split face value"),
            ("new_face_value", "NUMERIC(10,2)", "Post-split face value"),
            ("split_ratio", "VARCHAR(20)", "Split ratio e.g. 10:1"),
        ],
    },
    {
        "num": 40, "name": "Rights Issues", "url": "/v1/rights/{symbol}",
        "freq": "EOD", "update": "22:05 IST",
        "inputs": [("symbol", "NSE symbol"), ("from_date", "Start"), ("to_date", "End")],
        "outputs": [
            ("rights_id", "BIGINT", "Primary key"),
            ("symbol", "VARCHAR(20)", "Symbol"),
            ("announcement_date", "DATE", "Announcement date"),
            ("ex_date", "DATE", "Ex-rights date"),
            ("record_date", "DATE", "Record date"),
            ("issue_open_date", "DATE", "Rights issue open date"),
            ("issue_close_date", "DATE", "Rights issue close date"),
            ("ratio", "VARCHAR(20)", "Entitlement ratio"),
            ("rights_price", "NUMERIC(14,4)", "Subscription price"),
            ("issue_size_cr", "NUMERIC(14,2)", "Total issue size in crores"),
            ("purpose", "TEXT", "Use of proceeds"),
        ],
    },
    {
        "num": 41, "name": "Buybacks", "url": "/v1/buybacks/{symbol}",
        "freq": "EOD", "update": "22:05 IST",
        "inputs": [("symbol", "NSE symbol"), ("from_date", "Start"), ("to_date", "End")],
        "outputs": [
            ("buyback_id", "BIGINT", "Primary key"),
            ("symbol", "VARCHAR(20)", "Symbol"),
            ("announcement_date", "DATE", "Announcement date"),
            ("record_date", "DATE", "Record date"),
            ("open_date", "DATE", "Buyback open date"),
            ("close_date", "DATE", "Buyback close date"),
            ("method", "VARCHAR(20)", "Tender or Open Market"),
            ("buyback_price", "NUMERIC(14,4)", "Offer price"),
            ("total_size_cr", "NUMERIC(14,2)", "Total buyback size in crores"),
            ("shares_offered", "BIGINT", "Total shares offered for buyback"),
            ("acceptance_ratio_pct", "NUMERIC(8,4)", "Final acceptance ratio"),
            ("status", "VARCHAR(20)", "Announced/Open/Completed"),
        ],
    },
    {
        "num": 42, "name": "Mergers & Demergers", "url": "/v1/mergers/{symbol}",
        "freq": "EOD", "update": "22:05 IST",
        "inputs": [("symbol", "NSE symbol"), ("from_date", "Start"), ("to_date", "End")],
        "outputs": [
            ("event_id", "BIGINT", "Primary key"),
            ("symbol", "VARCHAR(20)", "Symbol"),
            ("event_type", "VARCHAR(30)", "merger/demerger/amalgamation/scheme_of_arrangement"),
            ("counterparty_symbol", "VARCHAR(20)", "Other entity symbol if listed"),
            ("counterparty_name", "VARCHAR(255)", "Other entity name"),
            ("announcement_date", "DATE", "Announcement date"),
            ("effective_date", "DATE", "Effective date"),
            ("record_date", "DATE", "Record date"),
            ("share_swap_ratio", "VARCHAR(20)", "Share swap ratio e.g. 5:1"),
            ("status", "VARCHAR(30)", "Announced/Court_Approved/Effective"),
            ("description", "TEXT", "Full event description"),
        ],
    },
    {
        "num": 43, "name": "Board Meetings", "url": "/v1/board-meetings",
        "freq": "Daily", "update": "22:00 IST",
        "inputs": [
            ("symbol", "Filter by symbol"),
            ("from_date", "Start date"),
            ("to_date", "End date"),
            ("purpose", "results/dividend/fund_raise/other"),
        ],
        "outputs": [
            ("meeting_id", "BIGINT", "Primary key"),
            ("symbol", "VARCHAR(20)", "Symbol"),
            ("meeting_date", "DATE", "Scheduled meeting date"),
            ("purpose", "VARCHAR(100)", "Meeting purpose"),
            ("description", "TEXT", "Full description"),
            ("announcement_date", "DATE", "Date announced"),
            ("source", "VARCHAR(10)", "BSE or NSE"),
        ],
    },
    {
        "num": 44, "name": "AGM/EGM Calendar", "url": "/v1/agm-egm",
        "freq": "Daily", "update": "22:00 IST",
        "inputs": [
            ("symbol", "Symbol filter"),
            ("from_date", "Start"),
            ("to_date", "End"),
            ("meeting_type", "AGM or EGM"),
        ],
        "outputs": [
            ("id", "BIGINT", "Primary key"),
            ("symbol", "VARCHAR(20)", "Symbol"),
            ("meeting_type", "VARCHAR(10)", "AGM or EGM"),
            ("meeting_date", "DATE", "Scheduled date"),
            ("record_date", "DATE", "Record date for voting"),
            ("venue", "TEXT", "Meeting venue"),
            ("agenda", "TEXT", "Meeting agenda summary"),
            ("voting_period_start", "DATE", "E-voting start date"),
            ("voting_period_end", "DATE", "E-voting end date"),
        ],
    },
    {
        "num": 45, "name": "Corporate Announcements", "url": "/v1/announcements",
        "freq": "15-min", "update": "Every 15 minutes 09:00-18:00 IST",
        "inputs": [
            ("symbol", "Symbol filter"),
            ("category", "financial/management_change/strategic/regulatory"),
            ("from_datetime", "Start datetime"),
            ("to_datetime", "End datetime"),
            ("page,limit", "Pagination"),
        ],
        "outputs": [
            ("announcement_id", "BIGINT", "Primary key"),
            ("symbol", "VARCHAR(20)", "Symbol"),
            ("bse_code", "INTEGER", "BSE code if applicable"),
            ("subject", "VARCHAR(500)", "One-line subject"),
            ("category", "VARCHAR(50)", "Announcement category"),
            ("sub_category", "VARCHAR(100)", "Sub-category"),
            ("description", "TEXT", "Full body"),
            ("attachment_url", "VARCHAR(500)", "PDF attachment URL"),
            ("submitted_at_ist", "TIMESTAMP", "Submission time"),
            ("disseminated_at_ist", "TIMESTAMP", "Public dissemination time"),
            ("is_price_sensitive", "BOOLEAN", "Material/price-sensitive flag"),
            ("exchange", "VARCHAR(5)", "BSE or NSE"),
            ("url_hash", "CHAR(64)", "Idempotency key (SHA256 of URL)"),
        ],
    },
    {
        "num": 46, "name": "Face Value Changes", "url": "/v1/face-value-changes/{symbol}",
        "freq": "EOD", "update": "22:00 IST",
        "inputs": [("symbol", "NSE symbol"), ("from_date", "Start"), ("to_date", "End")],
        "outputs": [
            ("change_id", "BIGINT", "Primary key"),
            ("symbol", "VARCHAR(20)", "Symbol"),
            ("effective_date", "DATE", "Date of face value change"),
            ("old_face_value", "NUMERIC(10,2)", "Previous face value"),
            ("new_face_value", "NUMERIC(10,2)", "New face value"),
            ("reason", "VARCHAR(100)", "Reason e.g. split/consolidation"),
            ("ratio", "VARCHAR(20)", "Change ratio"),
        ],
    },
    {
        "num": 47, "name": "Share Capital Changes", "url": "/v1/share-capital/{symbol}",
        "freq": "EOD", "update": "22:00 IST",
        "inputs": [("symbol", "NSE symbol"), ("from_date", "Start"), ("to_date", "End")],
        "outputs": [
            ("change_id", "BIGINT", "Primary key"),
            ("symbol", "VARCHAR(20)", "Symbol"),
            ("change_date", "DATE", "Effective date"),
            ("change_type", "VARCHAR(50)", "Bonus/Rights/Buyback/ESOP/Preferential/QIP"),
            ("shares_before", "BIGINT", "Outstanding shares before change"),
            ("shares_after", "BIGINT", "Outstanding shares after change"),
            ("shares_added", "BIGINT", "Net shares added (negative for buybacks)"),
            ("paid_up_capital_before_cr", "NUMERIC(18,2)", "Paid-up capital before"),
            ("paid_up_capital_after_cr", "NUMERIC(18,2)", "Paid-up capital after"),
            ("issue_price", "NUMERIC(14,4)", "Issue or allotment price"),
        ],
    },
    {
        "num": 48, "name": "F&O Symbol Master", "url": "/v1/fno/symbols",
        "freq": "Daily", "update": "09:00 IST",
        "inputs": [
            ("instrument_type", "FUTSTK/FUTIDX/OPTSTK/OPTIDX"),
            ("underlying", "Underlying symbol"),
        ],
        "outputs": [
            ("instrument_id", "BIGINT", "Primary key"),
            ("instrument_type", "VARCHAR(10)", "FUTSTK/FUTIDX/OPTSTK/OPTIDX"),
            ("underlying", "VARCHAR(20)", "Underlying symbol"),
            ("expiry_date", "DATE", "Contract expiry"),
            ("strike_price", "NUMERIC(14,4)", "Strike (null for futures)"),
            ("option_type", "VARCHAR(2)", "CE/PE (null for futures)"),
            ("lot_size", "INTEGER", "Contract lot size"),
            ("tick_size", "NUMERIC(8,4)", "Minimum price movement"),
            ("is_active", "BOOLEAN", "Currently tradeable"),
            ("last_trade_date", "DATE", "Last trade date"),
        ],
    },
    {
        "num": 49, "name": "Futures Quote", "url": "/v1/fno/futures/{symbol}",
        "freq": "Real-time", "update": "Every 5 seconds during market hours",
        "inputs": [("symbol", "Underlying symbol"), ("expiry", "Contract expiry date")],
        "outputs": [
            ("instrument_id", "BIGINT", "Primary key"),
            ("symbol", "VARCHAR(20)", "Underlying"),
            ("expiry_date", "DATE", "Contract expiry"),
            ("ltp", "NUMERIC(14,4)", "Last traded price"),
            ("change", "NUMERIC(14,4)", "Change vs prev close"),
            ("change_pct", "NUMERIC(10,4)", "Percentage change"),
            ("open", "NUMERIC(14,4)", "Day open"),
            ("high", "NUMERIC(14,4)", "Day high"),
            ("low", "NUMERIC(14,4)", "Day low"),
            ("prev_close", "NUMERIC(14,4)", "Previous close"),
            ("volume", "BIGINT", "Volume traded"),
            ("value_cr", "NUMERIC(18,4)", "Value in crores"),
            ("open_interest", "BIGINT", "Current OI"),
            ("oi_change", "BIGINT", "Change in OI"),
            ("oi_change_pct", "NUMERIC(10,4)", "OI change %"),
            ("bid_price", "NUMERIC(14,4)", "Best bid"),
            ("ask_price", "NUMERIC(14,4)", "Best ask"),
            ("bid_qty", "INTEGER", "Bid quantity"),
            ("ask_qty", "INTEGER", "Ask quantity"),
            ("basis", "NUMERIC(14,4)", "Futures minus spot price"),
            ("cost_of_carry_pct", "NUMERIC(10,4)", "Implied cost of carry"),
            ("timestamp_ist", "TIMESTAMP", "Snapshot time"),
        ],
    },
    {
        "num": 50, "name": "Options Chain", "url": "/v1/fno/options/{symbol}/chain",
        "freq": "Real-time", "update": "Every 5 seconds",
        "inputs": [("symbol", "Underlying"), ("expiry", "Expiry date")],
        "outputs": [
            ("symbol", "VARCHAR(20)", "Underlying symbol"),
            ("expiry_date", "DATE", "Expiry date"),
            ("spot_price", "NUMERIC(14,4)", "Underlying spot price"),
            ("strikes", "JSONB", "Array of strike rows {strike, ce_*, pe_*, iv, oi, volume}"),
            ("pcr", "NUMERIC(10,4)", "Put-Call Ratio (total PE OI / total CE OI)"),
            ("max_pain_strike", "NUMERIC(14,4)", "Max pain strike price"),
            ("timestamp_ist", "TIMESTAMP", "Snapshot time"),
        ],
    },
    {
        "num": 51, "name": "Option Greeks", "url": "/v1/fno/options/{symbol}/greeks",
        "freq": "Real-time", "update": "Calculated every snapshot",
        "inputs": [
            ("symbol", "Underlying"),
            ("expiry", "Expiry date"),
            ("strike", "Strike price"),
            ("option_type", "CE or PE"),
        ],
        "outputs": [
            ("instrument_id", "BIGINT", "Primary key"),
            ("delta", "NUMERIC(10,6)", "Price sensitivity to underlying"),
            ("gamma", "NUMERIC(10,8)", "Rate of change of delta"),
            ("theta", "NUMERIC(12,6)", "Time decay per day"),
            ("vega", "NUMERIC(12,6)", "Sensitivity to IV"),
            ("rho", "NUMERIC(12,6)", "Interest rate sensitivity"),
            ("iv", "NUMERIC(10,4)", "Implied volatility %"),
            ("theoretical_price", "NUMERIC(14,4)", "Black-Scholes theoretical price"),
        ],
    },
    {
        "num": 52, "name": "Open Interest History", "url": "/v1/fno/oi/{symbol}",
        "freq": "Real-time", "update": "Every 5 seconds",
        "inputs": [
            ("symbol", "Underlying"),
            ("expiry", "Expiry"),
            ("from_datetime", "Start"),
            ("to_datetime", "End"),
        ],
        "outputs": [
            ("instrument_id", "BIGINT", "Instrument ID"),
            ("timestamp_ist", "TIMESTAMP", "Snapshot time"),
            ("oi", "BIGINT", "Open Interest"),
            ("oi_change", "BIGINT", "OI change from previous snapshot"),
            ("oi_change_pct", "NUMERIC(10,4)", "OI change %"),
            ("volume", "BIGINT", "Snapshot volume"),
            ("price", "NUMERIC(14,4)", "Reference price"),
        ],
    },
    {
        "num": 53, "name": "OI Buildup", "url": "/v1/fno/oi-buildup",
        "freq": "5-min", "update": "Every 5 minutes",
        "inputs": [
            ("signal_type", "long_buildup/short_buildup/long_unwinding/short_covering"),
            ("instrument_type", "FUT or OPT"),
        ],
        "outputs": [
            ("symbol", "VARCHAR(20)", "Underlying"),
            ("signal_type", "VARCHAR(30)", "Buildup classification"),
            ("price_change_pct", "NUMERIC(10,4)", "Price change %"),
            ("oi_change_pct", "NUMERIC(10,4)", "OI change %"),
            ("volume", "BIGINT", "Snapshot volume"),
            ("oi", "BIGINT", "Current OI"),
            ("timestamp_ist", "TIMESTAMP", "Snapshot time"),
        ],
    },
    {
        "num": 54, "name": "Most Active F&O", "url": "/v1/fno/most-active",
        "freq": "Real-time", "update": "Every 5 minutes",
        "inputs": [
            ("metric", "volume/value/oi"),
            ("instrument_type", "FUTSTK/OPTSTK/FUTIDX/OPTIDX"),
            ("limit", "Result count"),
        ],
        "outputs": [
            ("rank", "INTEGER", "Rank by chosen metric"),
            ("symbol", "VARCHAR(20)", "Underlying"),
            ("expiry_date", "DATE", "Expiry"),
            ("ltp", "NUMERIC(14,4)", "Last price"),
            ("change_pct", "NUMERIC(10,4)", "Change %"),
            ("volume", "BIGINT", "Volume"),
            ("value_cr", "NUMERIC(18,4)", "Value in crores"),
            ("oi", "BIGINT", "Open Interest"),
            ("oi_change_pct", "NUMERIC(10,4)", "OI change %"),
        ],
    },
    {
        "num": 55, "name": "Put-Call Ratio", "url": "/v1/fno/pcr/{symbol}",
        "freq": "Real-time", "update": "Every 5 minutes",
        "inputs": [
            ("symbol", "Underlying"),
            ("expiry", "Expiry"),
            ("from_datetime", "Start"),
            ("to_datetime", "End"),
        ],
        "outputs": [
            ("symbol", "VARCHAR(20)", "Underlying"),
            ("expiry_date", "DATE", "Expiry"),
            ("pcr_oi", "NUMERIC(10,4)", "PCR based on OI"),
            ("pcr_volume", "NUMERIC(10,4)", "PCR based on volume"),
            ("timestamp_ist", "TIMESTAMP", "Snapshot time"),
        ],
    },
    {
        "num": 56, "name": "F&O Lot Size History", "url": "/v1/fno/lot-size",
        "freq": "Monthly", "update": "NSE revisions notification day",
        "inputs": [("symbol", "Underlying"), ("as_of_date", "Snapshot date")],
        "outputs": [
            ("symbol", "VARCHAR(20)", "Underlying"),
            ("lot_size", "INTEGER", "Contract lot size"),
            ("effective_from", "DATE", "Effective from date"),
            ("effective_to", "DATE", "Effective until date"),
        ],
    },
    {
        "num": 57, "name": "Block Deals", "url": "/v1/block-deals",
        "freq": "EOD", "update": "18:45 IST",
        "inputs": [
            ("symbol", "Symbol filter"),
            ("from_date", "Start"),
            ("to_date", "End"),
            ("client_name", "Substring match on client name"),
        ],
        "outputs": [
            ("deal_id", "BIGINT", "Primary key"),
            ("trade_date", "DATE", "Trade date"),
            ("symbol", "VARCHAR(20)", "Symbol"),
            ("deal_type", "VARCHAR(10)", "block"),
            ("client_name", "VARCHAR(255)", "Counterparty name"),
            ("action", "VARCHAR(4)", "BUY or SELL"),
            ("quantity", "BIGINT", "Shares traded"),
            ("price", "NUMERIC(14,4)", "Trade price"),
            ("value_cr", "NUMERIC(18,4)", "Trade value in crores"),
            ("exchange", "VARCHAR(5)", "NSE or BSE"),
        ],
    },
    {
        "num": 58, "name": "Bulk Deals", "url": "/v1/bulk-deals",
        "freq": "EOD", "update": "18:45 IST",
        "inputs": [
            ("symbol", "Symbol filter"),
            ("from_date", "Start"),
            ("to_date", "End"),
            ("client_name", "Substring search"),
        ],
        "outputs": [
            ("deal_id", "BIGINT", "Primary key"),
            ("trade_date", "DATE", "Trade date"),
            ("symbol", "VARCHAR(20)", "Symbol"),
            ("deal_type", "VARCHAR(10)", "bulk"),
            ("client_name", "VARCHAR(255)", "Client name"),
            ("action", "VARCHAR(4)", "BUY or SELL"),
            ("quantity", "BIGINT", "Shares"),
            ("price", "NUMERIC(14,4)", "Weighted average price"),
            ("value_cr", "NUMERIC(18,4)", "Value in crores"),
            ("exchange", "VARCHAR(5)", "Exchange code"),
        ],
    },
    {
        "num": 59, "name": "Insider Trading (SAST)", "url": "/v1/insider-trading/{symbol}",
        "freq": "Daily", "update": "Hourly polling of BSE SAST filings",
        "inputs": [
            ("symbol", "NSE symbol"),
            ("from_date", "Start"),
            ("to_date", "End"),
            ("transaction_type", "buy or sell"),
        ],
        "outputs": [
            ("trade_id", "BIGINT", "Primary key"),
            ("symbol", "VARCHAR(20)", "Symbol"),
            ("acquirer_name", "VARCHAR(255)", "Acquirer or disposer name"),
            ("acquirer_category", "VARCHAR(50)", "Promoter/KMP/Director/Connected"),
            ("transaction_type", "VARCHAR(20)", "BUY/SELL/PLEDGE/INVOKED"),
            ("transaction_date", "DATE", "Trade date"),
            ("intimation_date", "DATE", "Disclosure date to exchange"),
            ("quantity", "BIGINT", "Shares traded"),
            ("value_cr", "NUMERIC(18,4)", "Value in crores"),
            ("avg_price", "NUMERIC(14,4)", "Weighted average price"),
            ("pre_transaction_holding_pct", "NUMERIC(8,4)", "Holding before transaction"),
            ("post_transaction_holding_pct", "NUMERIC(8,4)", "Holding after transaction"),
            ("mode", "VARCHAR(50)", "Market Purchase/Off Market/Bonus/Gift/ESOP"),
        ],
    },
    {
        "num": 60, "name": "Pledged Shares", "url": "/v1/pledged-shares/{symbol}",
        "freq": "Quarterly", "update": "With shareholding pattern release",
        "inputs": [
            ("symbol", "NSE symbol"),
            ("from_period", "Start period"),
            ("to_period", "End period"),
        ],
        "outputs": [
            ("id", "BIGINT", "Primary key"),
            ("symbol", "VARCHAR(20)", "Symbol"),
            ("period", "VARCHAR(15)", "Quarter e.g. FY2025-Q3"),
            ("period_end_date", "DATE", "Period end date"),
            ("promoter_name", "VARCHAR(255)", "Promoter name"),
            ("total_shares_held", "BIGINT", "Total shares held by promoter"),
            ("pledged_shares", "BIGINT", "Pledged shares"),
            ("pledged_pct_of_holding", "NUMERIC(8,4)", "Pledge as % of holding"),
            ("pledged_pct_of_total_equity", "NUMERIC(8,4)", "Pledge as % of total equity"),
            ("change_qoq_shares", "BIGINT", "Quarter-on-quarter change"),
            ("encumbered_shares", "BIGINT", "Encumbered shares (broader than pledge)"),
        ],
    },
    {
        "num": 61, "name": "Quarterly Results", "url": "/v1/financials/{symbol}/quarterly",
        "freq": "Quarterly", "update": "Within 45 days of quarter-end",
        "inputs": [
            ("symbol", "NSE symbol"),
            ("from_period", "Start quarter"),
            ("to_period", "End quarter"),
            ("consolidated", "Consolidated or standalone (default true)"),
        ],
        "outputs": [
            ("result_id", "BIGINT", "Primary key"),
            ("symbol", "VARCHAR(20)", "Symbol"),
            ("period", "VARCHAR(15)", "Quarter e.g. FY2025-Q3"),
            ("period_end_date", "DATE", "Quarter ending date"),
            ("consolidated", "BOOLEAN", "Consolidated flag"),
            ("revenue_cr", "NUMERIC(18,2)", "Total revenue from operations"),
            ("other_income_cr", "NUMERIC(18,2)", "Other income"),
            ("total_income_cr", "NUMERIC(18,2)", "Total income"),
            ("raw_material_cost_cr", "NUMERIC(18,2)", "Cost of materials consumed"),
            ("employee_cost_cr", "NUMERIC(18,2)", "Employee benefit expenses"),
            ("finance_cost_cr", "NUMERIC(18,2)", "Finance costs"),
            ("depreciation_cr", "NUMERIC(18,2)", "Depreciation and amortization"),
            ("other_expense_cr", "NUMERIC(18,2)", "Other expenses"),
            ("total_expense_cr", "NUMERIC(18,2)", "Total expenses"),
            ("ebitda_cr", "NUMERIC(18,2)", "EBITDA"),
            ("ebitda_margin_pct", "NUMERIC(8,4)", "EBITDA margin %"),
            ("ebit_cr", "NUMERIC(18,2)", "EBIT"),
            ("pbt_cr", "NUMERIC(18,2)", "Profit before tax"),
            ("tax_cr", "NUMERIC(18,2)", "Tax expense"),
            ("pat_cr", "NUMERIC(18,2)", "Profit after tax"),
            ("net_profit_margin_pct", "NUMERIC(8,4)", "Net profit margin %"),
            ("eps_basic", "NUMERIC(12,4)", "Basic EPS"),
            ("eps_diluted", "NUMERIC(12,4)", "Diluted EPS"),
            ("interim_dividend_per_share", "NUMERIC(10,4)", "Interim dividend per share"),
            ("result_date", "DATE", "Board meeting date for result"),
            ("auditor_status", "VARCHAR(30)", "audited/unaudited/limited_review"),
            ("yoy_revenue_growth_pct", "NUMERIC(10,4)", "YoY revenue growth"),
            ("yoy_pat_growth_pct", "NUMERIC(10,4)", "YoY PAT growth"),
            ("qoq_revenue_growth_pct", "NUMERIC(10,4)", "QoQ revenue growth"),
            ("qoq_pat_growth_pct", "NUMERIC(10,4)", "QoQ PAT growth"),
        ],
    },
    {
        "num": 62, "name": "Annual P&L", "url": "/v1/financials/{symbol}/profit-loss",
        "freq": "Annual", "update": "Within 60 days of FY-end",
        "inputs": [
            ("symbol", "NSE symbol"),
            ("from_fy", "Start FY"),
            ("to_fy", "End FY"),
            ("consolidated", "Consolidated flag"),
        ],
        "outputs": [
            ("pl_id", "BIGINT", "Primary key"),
            ("symbol", "VARCHAR(20)", "Symbol"),
            ("fy_year", "SMALLINT", "FY year e.g. 2025"),
            ("period_end_date", "DATE", "FY ending date"),
            ("consolidated", "BOOLEAN", "Consolidated flag"),
            ("revenue_cr", "NUMERIC(18,2)", "Total revenue"),
            ("total_income_cr", "NUMERIC(18,2)", "Total income"),
            ("ebitda_cr", "NUMERIC(18,2)", "EBITDA"),
            ("ebitda_margin_pct", "NUMERIC(8,4)", "EBITDA margin"),
            ("pbt_cr", "NUMERIC(18,2)", "PBT"),
            ("tax_cr", "NUMERIC(18,2)", "Tax"),
            ("pat_cr", "NUMERIC(18,2)", "PAT"),
            ("eps_basic", "NUMERIC(12,4)", "Basic EPS for FY"),
            ("eps_diluted", "NUMERIC(12,4)", "Diluted EPS"),
            ("dividend_per_share_total", "NUMERIC(10,4)", "Total DPS for FY"),
            ("book_value_per_share", "NUMERIC(14,4)", "Book value per share"),
            ("cash_eps", "NUMERIC(12,4)", "PAT + Depreciation per share"),
            ("effective_tax_rate_pct", "NUMERIC(8,4)", "Effective tax rate"),
        ],
    },
    {
        "num": 63, "name": "Balance Sheet", "url": "/v1/financials/{symbol}/balance-sheet",
        "freq": "Annual", "update": "Within 60 days of FY-end",
        "inputs": [
            ("symbol", "NSE symbol"),
            ("from_fy", "Start FY"),
            ("to_fy", "End FY"),
            ("consolidated", "Consolidated flag"),
        ],
        "outputs": [
            ("bs_id", "BIGINT", "Primary key"),
            ("symbol", "VARCHAR(20)", "Symbol"),
            ("fy_year", "SMALLINT", "FY year"),
            ("period_end_date", "DATE", "Period end"),
            ("consolidated", "BOOLEAN", "Consolidated"),
            ("equity_share_capital_cr", "NUMERIC(18,2)", "Equity share capital"),
            ("reserves_surplus_cr", "NUMERIC(18,2)", "Reserves & surplus"),
            ("total_shareholders_equity_cr", "NUMERIC(18,2)", "Total shareholder equity"),
            ("minority_interest_cr", "NUMERIC(18,2)", "Minority interest"),
            ("long_term_debt_cr", "NUMERIC(18,2)", "Long-term borrowings"),
            ("short_term_debt_cr", "NUMERIC(18,2)", "Short-term borrowings"),
            ("total_debt_cr", "NUMERIC(18,2)", "Total debt"),
            ("deferred_tax_liability_cr", "NUMERIC(18,2)", "Deferred tax liability"),
            ("trade_payables_cr", "NUMERIC(18,2)", "Trade payables"),
            ("other_current_liabilities_cr", "NUMERIC(18,2)", "Other current liabilities"),
            ("total_liabilities_cr", "NUMERIC(18,2)", "Total liabilities"),
            ("fixed_assets_cr", "NUMERIC(18,2)", "Net fixed assets"),
            ("capital_work_in_progress_cr", "NUMERIC(18,2)", "CWIP"),
            ("intangible_assets_cr", "NUMERIC(18,2)", "Intangibles incl goodwill"),
            ("investments_long_term_cr", "NUMERIC(18,2)", "Long-term investments"),
            ("investments_short_term_cr", "NUMERIC(18,2)", "Current investments"),
            ("inventories_cr", "NUMERIC(18,2)", "Inventories"),
            ("trade_receivables_cr", "NUMERIC(18,2)", "Trade receivables"),
            ("cash_equivalents_cr", "NUMERIC(18,2)", "Cash & equivalents"),
            ("other_current_assets_cr", "NUMERIC(18,2)", "Other current assets"),
            ("total_current_assets_cr", "NUMERIC(18,2)", "Total current assets"),
            ("total_non_current_assets_cr", "NUMERIC(18,2)", "Total non-current assets"),
            ("total_assets_cr", "NUMERIC(18,2)", "Total assets"),
            ("working_capital_cr", "NUMERIC(18,2)", "Current assets minus current liab"),
            ("net_worth_cr", "NUMERIC(18,2)", "Net worth"),
            ("debt_to_equity", "NUMERIC(10,4)", "Total debt / equity"),
        ],
    },
    {
        "num": 64, "name": "Cash Flow Statement", "url": "/v1/financials/{symbol}/cash-flow",
        "freq": "Annual", "update": "Within 60 days of FY-end",
        "inputs": [
            ("symbol", "NSE symbol"),
            ("from_fy", "Start FY"),
            ("to_fy", "End FY"),
            ("consolidated", "Consolidated flag"),
        ],
        "outputs": [
            ("cf_id", "BIGINT", "Primary key"),
            ("symbol", "VARCHAR(20)", "Symbol"),
            ("fy_year", "SMALLINT", "FY year"),
            ("period_end_date", "DATE", "Period end"),
            ("consolidated", "BOOLEAN", "Consolidated"),
            ("cash_from_operations_cr", "NUMERIC(18,2)", "CFO"),
            ("cash_from_investing_cr", "NUMERIC(18,2)", "CFI"),
            ("cash_from_financing_cr", "NUMERIC(18,2)", "CFF"),
            ("net_change_in_cash_cr", "NUMERIC(18,2)", "Net change in cash"),
            ("opening_cash_cr", "NUMERIC(18,2)", "Opening cash balance"),
            ("closing_cash_cr", "NUMERIC(18,2)", "Closing cash balance"),
            ("capex_cr", "NUMERIC(18,2)", "Capital expenditure"),
            ("free_cash_flow_cr", "NUMERIC(18,2)", "CFO - Capex"),
            ("dividend_paid_cr", "NUMERIC(18,2)", "Total dividend paid"),
            ("interest_paid_cr", "NUMERIC(18,2)", "Interest paid"),
            ("taxes_paid_cr", "NUMERIC(18,2)", "Taxes paid"),
        ],
    },
    {
        "num": 65, "name": "Financial Ratios (Latest)", "url": "/v1/ratios/{symbol}",
        "freq": "Quarterly", "update": "After results released",
        "inputs": [("symbol", "NSE symbol")],
        "outputs": [
            ("symbol", "VARCHAR(20)", "Symbol"),
            ("as_of_date", "DATE", "Snapshot date"),
            ("pe_ratio", "NUMERIC(10,4)", "Price to Earnings"),
            ("pb_ratio", "NUMERIC(10,4)", "Price to Book"),
            ("ps_ratio", "NUMERIC(10,4)", "Price to Sales"),
            ("ev_to_ebitda", "NUMERIC(10,4)", "Enterprise value to EBITDA"),
            ("peg_ratio", "NUMERIC(10,4)", "PE to Growth"),
            ("dividend_yield_pct", "NUMERIC(8,4)", "Dividend yield"),
            ("roe_pct", "NUMERIC(10,4)", "Return on Equity"),
            ("roce_pct", "NUMERIC(10,4)", "Return on Capital Employed"),
            ("roa_pct", "NUMERIC(10,4)", "Return on Assets"),
            ("net_profit_margin_pct", "NUMERIC(10,4)", "Net profit margin"),
            ("operating_margin_pct", "NUMERIC(10,4)", "Operating margin"),
            ("gross_margin_pct", "NUMERIC(10,4)", "Gross margin"),
            ("debt_to_equity", "NUMERIC(10,4)", "Debt to equity"),
            ("interest_coverage", "NUMERIC(10,4)", "EBIT to interest"),
            ("current_ratio", "NUMERIC(10,4)", "Current assets / liabilities"),
            ("quick_ratio", "NUMERIC(10,4)", "Quick ratio (acid test)"),
            ("inventory_turnover", "NUMERIC(10,4)", "Revenue / inventory"),
            ("receivables_days", "INTEGER", "Days sales outstanding"),
            ("payables_days", "INTEGER", "Days payable outstanding"),
            ("cash_conversion_cycle", "INTEGER", "Cash cycle in days"),
            ("asset_turnover", "NUMERIC(10,4)", "Revenue / total assets"),
            ("revenue_growth_ttm_pct", "NUMERIC(10,4)", "TTM revenue growth"),
            ("pat_growth_ttm_pct", "NUMERIC(10,4)", "TTM PAT growth"),
            ("eps_growth_ttm_pct", "NUMERIC(10,4)", "TTM EPS growth"),
            ("eps_ttm", "NUMERIC(12,4)", "Trailing 12-month EPS"),
            ("book_value_per_share", "NUMERIC(14,4)", "BV per share"),
            ("cash_per_share", "NUMERIC(14,4)", "Cash per share"),
            ("revenue_per_share", "NUMERIC(14,4)", "Revenue per share"),
            ("market_cap_cr", "NUMERIC(18,2)", "Market cap"),
            ("enterprise_value_cr", "NUMERIC(18,2)", "Enterprise value"),
            ("beta_1y", "NUMERIC(8,4)", "1-year beta vs Nifty"),
            ("updated_at", "TIMESTAMPTZ", "Last update"),
        ],
    },
]
