"""Mutual Fund APIs — comprehensive CMOTS-equivalent MF data."""

MF_APIS = [
    {
        "num": 1, "name": "AMC Master", "url": "/v1/mf/amcs",
        "freq": "Monthly", "update": "1st of month 03:00 IST",
        "inputs": [("is_active", "Active flag (default true)")],
        "outputs": [
            ("amc_id", "INTEGER", "Primary key"),
            ("amc_name", "VARCHAR(255)", "Full AMC name"),
            ("short_code", "VARCHAR(20)", "Short code e.g. HDFC"),
            ("registration_no", "VARCHAR(50)", "SEBI registration number"),
            ("incorporation_date", "DATE", "Date of AMC incorporation"),
            ("aum_cr", "NUMERIC(18,2)", "Latest total AUM in crores"),
            ("scheme_count", "SMALLINT", "Active scheme count"),
            ("website", "VARCHAR(255)", "AMC website"),
            ("email", "VARCHAR(255)", "AMC email"),
            ("phone", "VARCHAR(50)", "AMC phone"),
            ("trustee_name", "VARCHAR(255)", "Trustee company name"),
            ("sponsor_name", "VARCHAR(255)", "Sponsor entity"),
            ("is_active", "BOOLEAN", "Currently active flag"),
            ("updated_at", "TIMESTAMPTZ", "Last update"),
        ],
    },
    {
        "num": 2, "name": "Scheme Master", "url": "/v1/mf/schemes",
        "freq": "Weekly", "update": "Sunday 03:30 IST",
        "inputs": [
            ("amc_id", "Filter by AMC"),
            ("category", "Equity/Debt/Hybrid/Solution/Other"),
            ("sub_category", "Large Cap/Mid Cap/Liquid/etc"),
            ("is_direct", "Direct vs Regular filter"),
            ("is_active", "Active flag"),
            ("page,limit", "Pagination"),
        ],
        "outputs": [
            ("scheme_id", "BIGINT", "Primary key"),
            ("scheme_code", "VARCHAR(20)", "AMFI scheme code"),
            ("scheme_name", "VARCHAR(500)", "Full scheme name"),
            ("amc_id", "INTEGER", "AMC reference"),
            ("amc_name", "VARCHAR(255)", "AMC name"),
            ("isin_growth", "CHAR(12)", "ISIN for growth option"),
            ("isin_payout", "CHAR(12)", "ISIN for payout option"),
            ("isin_reinvest", "CHAR(12)", "ISIN for reinvestment"),
            ("category", "VARCHAR(100)", "SEBI category"),
            ("sub_category", "VARCHAR(100)", "SEBI sub-category"),
            ("plan_type", "VARCHAR(20)", "Direct or Regular"),
            ("option_type", "VARCHAR(30)", "Growth/IDCW/IDCW-Reinvestment"),
            ("launch_date", "DATE", "NFO close date"),
            ("closure_date", "DATE", "Closure date for closed-end"),
            ("min_investment_amount", "NUMERIC(12,2)", "Min lumpsum investment INR"),
            ("min_sip_amount", "NUMERIC(12,2)", "Min SIP installment INR"),
            ("min_additional_purchase", "NUMERIC(12,2)", "Min top-up amount"),
            ("min_redemption_amount", "NUMERIC(12,2)", "Min redemption amount"),
            ("exit_load_pct", "NUMERIC(6,4)", "Exit load %"),
            ("exit_load_period_days", "INTEGER", "Exit load applicable period"),
            ("benchmark_index", "VARCHAR(200)", "Benchmark name"),
            ("riskometer", "VARCHAR(50)", "SEBI riskometer level"),
            ("is_active", "BOOLEAN", "Currently active"),
            ("updated_at", "TIMESTAMPTZ", "Last update"),
        ],
    },
    {
        "num": 3, "name": "Fund Categories", "url": "/v1/mf/categories",
        "freq": "Monthly", "update": "1st of month 03:00 IST",
        "inputs": [("parent_category", "Filter by parent category")],
        "outputs": [
            ("category_id", "INTEGER", "Primary key"),
            ("category_name", "VARCHAR(100)", "Category name"),
            ("parent_category", "VARCHAR(100)", "Parent (Equity/Debt/Hybrid/etc)"),
            ("sebi_classification", "VARCHAR(200)", "SEBI scheme classification"),
            ("scheme_count", "INTEGER", "Active scheme count in category"),
            ("total_aum_cr", "NUMERIC(18,2)", "Total AUM in category"),
            ("avg_expense_ratio_pct", "NUMERIC(6,4)", "Category avg expense ratio"),
            ("description", "TEXT", "Category description and investment style"),
        ],
    },
    {
        "num": 4, "name": "Fund Types", "url": "/v1/mf/types",
        "freq": "Monthly", "update": "1st of month",
        "inputs": [],
        "outputs": [
            ("type_id", "INTEGER", "Primary key"),
            ("type_name", "VARCHAR(100)", "Type name e.g. Open Ended/Close Ended/Interval"),
            ("description", "TEXT", "Type description"),
            ("scheme_count", "INTEGER", "Scheme count of this type"),
            ("total_aum_cr", "NUMERIC(18,2)", "Total AUM"),
        ],
    },
    {
        "num": 5, "name": "Fund Manager Master", "url": "/v1/mf/managers",
        "freq": "Monthly", "update": "7th of month 03:30 IST",
        "inputs": [("amc_id", "AMC filter"), ("is_active", "Currently active")],
        "outputs": [
            ("manager_id", "BIGINT", "Primary key"),
            ("manager_name", "VARCHAR(255)", "Full name"),
            ("amc_id", "INTEGER", "Current AMC"),
            ("amc_name", "VARCHAR(255)", "Current AMC name"),
            ("designation", "VARCHAR(100)", "Designation"),
            ("schemes_managed_count", "INTEGER", "Count of schemes managed"),
            ("total_aum_managed_cr", "NUMERIC(18,2)", "Total AUM managed"),
            ("experience_years", "SMALLINT", "Years of experience"),
            ("qualification", "TEXT", "Qualifications"),
            ("prior_experience", "TEXT", "Prior employers/roles"),
            ("started_managing_funds_date", "DATE", "Date started as fund manager"),
            ("is_active", "BOOLEAN", "Currently active flag"),
        ],
    },
    {
        "num": 6, "name": "Daily NAV", "url": "/v1/mf/nav/{scheme_code}",
        "freq": "EOD", "update": "23:00 IST",
        "inputs": [
            ("scheme_code", "AMFI scheme code (path)"),
            ("nav_date", "Specific date (optional, default latest)"),
        ],
        "outputs": [
            ("scheme_code", "VARCHAR(20)", "Scheme code"),
            ("scheme_name", "VARCHAR(500)", "Scheme name"),
            ("amc_name", "VARCHAR(255)", "AMC name"),
            ("nav", "NUMERIC(14,4)", "NAV on date"),
            ("nav_date", "DATE", "NAV reference date"),
            ("change_1d", "NUMERIC(14,4)", "1-day change"),
            ("change_1d_pct", "NUMERIC(10,4)", "1-day change %"),
            ("repurchase_price", "NUMERIC(14,4)", "Repurchase price"),
            ("sale_price", "NUMERIC(14,4)", "Sale price"),
            ("last_updated", "TIMESTAMPTZ", "Last refresh"),
        ],
    },
    {
        "num": 7, "name": "NAV History", "url": "/v1/mf/nav/{scheme_code}/history",
        "freq": "EOD", "update": "23:00 IST",
        "inputs": [
            ("scheme_code", "Scheme code"),
            ("from_date", "Start date"),
            ("to_date", "End date"),
        ],
        "outputs": [
            ("scheme_code", "VARCHAR(20)", "Scheme code"),
            ("nav_date", "DATE", "NAV date"),
            ("nav", "NUMERIC(14,4)", "NAV value"),
            ("change_pct", "NUMERIC(10,4)", "Day change vs previous"),
            ("repurchase_price", "NUMERIC(14,4)", "Repurchase price"),
            ("sale_price", "NUMERIC(14,4)", "Sale price"),
        ],
    },
    {
        "num": 8, "name": "AUM History", "url": "/v1/mf/{scheme_code}/aum",
        "freq": "Monthly", "update": "7th of month 04:00 IST",
        "inputs": [
            ("scheme_code", "Scheme code"),
            ("from_month", "Start month"),
            ("to_month", "End month"),
        ],
        "outputs": [
            ("scheme_code", "VARCHAR(20)", "Scheme code"),
            ("as_of_month", "DATE", "Month end date"),
            ("aum_cr", "NUMERIC(18,2)", "AUM in crores"),
            ("aum_growth_mom_pct", "NUMERIC(10,4)", "MoM AUM growth %"),
            ("aum_growth_yoy_pct", "NUMERIC(10,4)", "YoY AUM growth %"),
            ("folio_count", "INTEGER", "Total folios"),
            ("net_subscription_cr", "NUMERIC(18,2)", "Net inflow this month"),
            ("net_redemption_cr", "NUMERIC(18,2)", "Net outflow this month"),
        ],
    },
    {
        "num": 9, "name": "Expense Ratio History", "url": "/v1/mf/{scheme_code}/expense-ratio",
        "freq": "Monthly", "update": "7th of month 04:00 IST",
        "inputs": [
            ("scheme_code", "Scheme code"),
            ("from_month", "Start"),
            ("to_month", "End"),
        ],
        "outputs": [
            ("scheme_code", "VARCHAR(20)", "Scheme code"),
            ("as_of_month", "DATE", "Month end"),
            ("total_expense_ratio_pct", "NUMERIC(6,4)", "Total expense ratio"),
            ("management_fee_pct", "NUMERIC(6,4)", "Management fee"),
            ("other_expenses_pct", "NUMERIC(6,4)", "Other expenses"),
            ("gst_pct", "NUMERIC(6,4)", "GST on fees"),
            ("category_avg_ter_pct", "NUMERIC(6,4)", "Category avg TER for comparison"),
        ],
    },
    {
        "num": 10, "name": "Risk Measures", "url": "/v1/mf/{scheme_code}/risk",
        "freq": "Daily", "update": "23:30 IST",
        "inputs": [
            ("scheme_code", "Scheme code"),
            ("as_of_date", "Calculation date"),
            ("lookback_years", "Lookback window (default 3)"),
        ],
        "outputs": [
            ("scheme_code", "VARCHAR(20)", "Scheme code"),
            ("as_of_date", "DATE", "Calculation date"),
            ("standard_deviation_pct", "NUMERIC(10,4)", "Annualized volatility"),
            ("beta", "NUMERIC(8,4)", "Beta vs benchmark"),
            ("alpha_pct", "NUMERIC(10,4)", "Jensen's alpha"),
            ("sharpe_ratio", "NUMERIC(10,4)", "Sharpe ratio"),
            ("sortino_ratio", "NUMERIC(10,4)", "Sortino ratio"),
            ("treynor_ratio", "NUMERIC(10,4)", "Treynor ratio"),
            ("r_squared", "NUMERIC(6,4)", "R-squared vs benchmark"),
            ("information_ratio", "NUMERIC(10,4)", "Information ratio"),
            ("max_drawdown_pct", "NUMERIC(10,4)", "Max drawdown %"),
            ("max_drawdown_date", "DATE", "Date of max drawdown"),
            ("tracking_error_pct", "NUMERIC(10,4)", "Tracking error vs benchmark"),
            ("downside_deviation_pct", "NUMERIC(10,4)", "Downside deviation"),
            ("var_95_pct", "NUMERIC(10,4)", "Value at Risk 95%"),
        ],
    },
    {
        "num": 11, "name": "Portfolio Holdings", "url": "/v1/mf/{scheme_code}/holdings",
        "freq": "Monthly", "update": "7th of month 04:30 IST",
        "inputs": [
            ("scheme_code", "Scheme code (path)"),
            ("as_of_month", "Snapshot month"),
            ("top_n", "Limit results"),
        ],
        "outputs": [
            ("holding_id", "BIGINT", "Primary key"),
            ("scheme_code", "VARCHAR(20)", "Scheme code"),
            ("as_of_month", "DATE", "Month end"),
            ("instrument_name", "VARCHAR(500)", "Instrument name"),
            ("instrument_type", "VARCHAR(30)", "Equity/Debt/Cash/Derivative/REIT"),
            ("isin", "CHAR(12)", "ISIN identifier"),
            ("symbol", "VARCHAR(20)", "NSE symbol for equity holdings"),
            ("sector", "VARCHAR(100)", "Sector for equity"),
            ("rating", "VARCHAR(10)", "Credit rating for debt"),
            ("shares_held", "BIGINT", "Quantity held"),
            ("face_value_cr", "NUMERIC(18,4)", "Face value in crores"),
            ("market_value_cr", "NUMERIC(18,4)", "Market value in crores"),
            ("weight_pct", "NUMERIC(8,4)", "Weight in scheme AUM"),
        ],
    },
    {
        "num": 12, "name": "Sector Allocation", "url": "/v1/mf/{scheme_code}/sector-allocation",
        "freq": "Monthly", "update": "7th of month",
        "inputs": [("scheme_code", "Scheme code"), ("as_of_month", "Month")],
        "outputs": [
            ("scheme_code", "VARCHAR(20)", "Scheme code"),
            ("as_of_month", "DATE", "Month end"),
            ("sector", "VARCHAR(100)", "Sector name"),
            ("weight_pct", "NUMERIC(8,4)", "Sector weight"),
            ("market_value_cr", "NUMERIC(18,4)", "Total value in sector"),
            ("holdings_count", "INTEGER", "Count of holdings in sector"),
            ("benchmark_sector_weight_pct", "NUMERIC(8,4)", "Benchmark sector weight for active share calc"),
            ("overweight_pct", "NUMERIC(8,4)", "Difference vs benchmark"),
        ],
    },
    {
        "num": 13, "name": "Asset Allocation", "url": "/v1/mf/{scheme_code}/asset-allocation",
        "freq": "Monthly", "update": "7th of month",
        "inputs": [("scheme_code", "Scheme code"), ("as_of_month", "Month")],
        "outputs": [
            ("scheme_code", "VARCHAR(20)", "Scheme code"),
            ("as_of_month", "DATE", "Month end"),
            ("equity_pct", "NUMERIC(8,4)", "Equity allocation %"),
            ("debt_pct", "NUMERIC(8,4)", "Debt allocation %"),
            ("cash_pct", "NUMERIC(8,4)", "Cash & equivalents %"),
            ("derivative_pct", "NUMERIC(8,4)", "Derivatives %"),
            ("reit_pct", "NUMERIC(8,4)", "REIT %"),
            ("commodity_pct", "NUMERIC(8,4)", "Commodity %"),
            ("foreign_securities_pct", "NUMERIC(8,4)", "Overseas allocation %"),
            ("large_cap_pct", "NUMERIC(8,4)", "Large cap %"),
            ("mid_cap_pct", "NUMERIC(8,4)", "Mid cap %"),
            ("small_cap_pct", "NUMERIC(8,4)", "Small cap %"),
            ("sovereign_pct", "NUMERIC(8,4)", "Sovereign rated debt %"),
            ("aaa_pct", "NUMERIC(8,4)", "AAA rated debt %"),
            ("aa_pct", "NUMERIC(8,4)", "AA rated debt %"),
            ("below_aa_pct", "NUMERIC(8,4)", "Below AA rated debt %"),
            ("modified_duration_years", "NUMERIC(8,4)", "Modified duration (debt)"),
            ("ytm_pct", "NUMERIC(8,4)", "Yield to maturity (debt)"),
            ("avg_maturity_years", "NUMERIC(8,4)", "Average maturity (debt)"),
        ],
    },
    {
        "num": 14, "name": "Top Holdings", "url": "/v1/mf/{scheme_code}/top-holdings",
        "freq": "Monthly", "update": "7th of month",
        "inputs": [
            ("scheme_code", "Scheme code"),
            ("as_of_month", "Month"),
            ("n", "Top N (default 10)"),
        ],
        "outputs": [
            ("scheme_code", "VARCHAR(20)", "Scheme code"),
            ("as_of_month", "DATE", "Month end"),
            ("rank", "INTEGER", "Holding rank"),
            ("instrument_name", "VARCHAR(500)", "Instrument name"),
            ("symbol", "VARCHAR(20)", "Symbol if equity"),
            ("sector", "VARCHAR(100)", "Sector"),
            ("weight_pct", "NUMERIC(8,4)", "Weight in AUM"),
            ("market_value_cr", "NUMERIC(18,4)", "Position value"),
        ],
    },
    {
        "num": 15, "name": "Returns", "url": "/v1/mf/{scheme_code}/returns",
        "freq": "Daily", "update": "23:30 IST",
        "inputs": [("scheme_code", "Scheme code"), ("as_of_date", "Reference date")],
        "outputs": [
            ("scheme_code", "VARCHAR(20)", "Scheme code"),
            ("as_of_date", "DATE", "Reference date"),
            ("returns_1d_pct", "NUMERIC(10,4)", "1-day return"),
            ("returns_1w_pct", "NUMERIC(10,4)", "1-week return"),
            ("returns_1m_pct", "NUMERIC(10,4)", "1-month return"),
            ("returns_3m_pct", "NUMERIC(10,4)", "3-month return"),
            ("returns_6m_pct", "NUMERIC(10,4)", "6-month return"),
            ("returns_1y_pct", "NUMERIC(10,4)", "1-year absolute return"),
            ("returns_3y_cagr_pct", "NUMERIC(10,4)", "3-year CAGR"),
            ("returns_5y_cagr_pct", "NUMERIC(10,4)", "5-year CAGR"),
            ("returns_10y_cagr_pct", "NUMERIC(10,4)", "10-year CAGR"),
            ("returns_since_inception_cagr_pct", "NUMERIC(10,4)", "Since-inception CAGR"),
            ("returns_ytd_pct", "NUMERIC(10,4)", "Year-to-date return"),
        ],
    },
    {
        "num": 16, "name": "SIP Returns", "url": "/v1/mf/{scheme_code}/sip-returns",
        "freq": "Daily", "update": "23:30 IST",
        "inputs": [
            ("scheme_code", "Scheme code"),
            ("sip_amount", "Monthly SIP amount (default 5000)"),
            ("frequency", "monthly/quarterly"),
            ("from_date", "SIP start date"),
            ("to_date", "SIP end date"),
        ],
        "outputs": [
            ("scheme_code", "VARCHAR(20)", "Scheme code"),
            ("sip_amount", "NUMERIC(12,2)", "SIP installment"),
            ("frequency", "VARCHAR(20)", "SIP frequency"),
            ("from_date", "DATE", "Start date"),
            ("to_date", "DATE", "End date"),
            ("total_invested", "NUMERIC(18,2)", "Total amount invested"),
            ("current_value", "NUMERIC(18,2)", "Current value of SIP corpus"),
            ("absolute_return_pct", "NUMERIC(10,4)", "Absolute return %"),
            ("xirr_pct", "NUMERIC(10,4)", "Extended internal rate of return (annualized)"),
            ("units_accumulated", "NUMERIC(18,4)", "Total units owned"),
        ],
    },
    {
        "num": 17, "name": "Rolling Returns", "url": "/v1/mf/{scheme_code}/rolling-returns",
        "freq": "Daily", "update": "23:45 IST",
        "inputs": [
            ("scheme_code", "Scheme code"),
            ("rolling_period", "Rolling window 1y/3y/5y"),
            ("from_date", "Start"),
            ("to_date", "End"),
        ],
        "outputs": [
            ("scheme_code", "VARCHAR(20)", "Scheme code"),
            ("rolling_period", "VARCHAR(5)", "Window e.g. 3y"),
            ("as_of_date", "DATE", "End of rolling window"),
            ("return_pct", "NUMERIC(10,4)", "Return for this window"),
            ("avg_rolling_return_pct", "NUMERIC(10,4)", "Average of all rolling windows"),
            ("median_rolling_return_pct", "NUMERIC(10,4)", "Median rolling return"),
            ("min_rolling_return_pct", "NUMERIC(10,4)", "Worst rolling return"),
            ("max_rolling_return_pct", "NUMERIC(10,4)", "Best rolling return"),
            ("positive_periods_pct", "NUMERIC(8,4)", "% of windows with positive return"),
        ],
    },
    {
        "num": 18, "name": "Exit Load", "url": "/v1/mf/{scheme_code}/exit-load",
        "freq": "Monthly", "update": "Scheme document refresh",
        "inputs": [("scheme_code", "Scheme code")],
        "outputs": [
            ("scheme_code", "VARCHAR(20)", "Scheme code"),
            ("exit_load_pct", "NUMERIC(6,4)", "Exit load percentage"),
            ("exit_load_period_days", "INTEGER", "Period in days within which load applies"),
            ("conditions", "TEXT", "Load conditions and tiers"),
            ("effective_from", "DATE", "Effective date"),
            ("notes", "TEXT", "Additional notes"),
        ],
    },
    {
        "num": 19, "name": "Entry Load (Historical)", "url": "/v1/mf/{scheme_code}/entry-load",
        "freq": "Annual", "update": "When scheme document changes (entry load banned post-2009)",
        "inputs": [("scheme_code", "Scheme code"), ("from_date", "Start"), ("to_date", "End")],
        "outputs": [
            ("scheme_code", "VARCHAR(20)", "Scheme code"),
            ("effective_from", "DATE", "Effective start"),
            ("effective_to", "DATE", "Effective end"),
            ("entry_load_pct", "NUMERIC(6,4)", "Entry load %"),
            ("notes", "TEXT", "Notes (entry load discontinued in 2009 by SEBI)"),
        ],
    },
    {
        "num": 20, "name": "Fund Ratings", "url": "/v1/mf/{scheme_code}/ratings",
        "freq": "Monthly", "update": "10th of month 04:00 IST",
        "inputs": [("scheme_code", "Scheme code")],
        "outputs": [
            ("scheme_code", "VARCHAR(20)", "Scheme code"),
            ("as_of_month", "DATE", "Rating month"),
            ("crisil_rating", "VARCHAR(20)", "CRISIL ranking"),
            ("morningstar_rating", "VARCHAR(5)", "Morningstar stars (1-5)"),
            ("value_research_rating", "VARCHAR(5)", "Value Research stars"),
            ("composite_score", "NUMERIC(5,2)", "Composite internal score 0-100"),
            ("category_rank", "INTEGER", "Rank within category"),
            ("category_total", "INTEGER", "Total schemes in category"),
            ("percentile", "NUMERIC(5,2)", "Percentile in category"),
        ],
    },
    {
        "num": 21, "name": "Benchmark Details", "url": "/v1/mf/{scheme_code}/benchmark",
        "freq": "Monthly", "update": "When SID updates",
        "inputs": [("scheme_code", "Scheme code")],
        "outputs": [
            ("scheme_code", "VARCHAR(20)", "Scheme code"),
            ("benchmark_name", "VARCHAR(200)", "Benchmark index name"),
            ("benchmark_type", "VARCHAR(50)", "Total Return Index/Price Return"),
            ("additional_benchmark", "VARCHAR(200)", "Optional additional benchmark"),
            ("effective_from", "DATE", "Effective from"),
            ("notes", "TEXT", "Notes on methodology"),
        ],
    },
    {
        "num": 22, "name": "Benchmark Comparison", "url": "/v1/mf/{scheme_code}/benchmark-comparison",
        "freq": "Daily", "update": "23:30 IST",
        "inputs": [
            ("scheme_code", "Scheme code"),
            ("as_of_date", "Reference date"),
            ("lookback_period", "1y/3y/5y/since_inception"),
        ],
        "outputs": [
            ("scheme_code", "VARCHAR(20)", "Scheme code"),
            ("benchmark_index", "VARCHAR(200)", "Benchmark"),
            ("scheme_return_pct", "NUMERIC(10,4)", "Scheme return"),
            ("benchmark_return_pct", "NUMERIC(10,4)", "Benchmark return"),
            ("outperformance_pct", "NUMERIC(10,4)", "Outperformance vs benchmark"),
            ("category_avg_return_pct", "NUMERIC(10,4)", "Category average return"),
            ("vs_category_pct", "NUMERIC(10,4)", "Outperformance vs category avg"),
            ("lookback_period", "VARCHAR(20)", "Window"),
        ],
    },
    {
        "num": 23, "name": "Scheme Changes", "url": "/v1/mf/{scheme_code}/changes",
        "freq": "Quarterly", "update": "Within 30 days of change",
        "inputs": [("scheme_code", "Scheme code"), ("from_date", "Start"), ("to_date", "End")],
        "outputs": [
            ("change_id", "BIGINT", "Primary key"),
            ("scheme_code", "VARCHAR(20)", "Scheme code"),
            ("change_date", "DATE", "Effective date"),
            ("change_type", "VARCHAR(50)", "Name/Type/Category/Benchmark/Manager"),
            ("old_value", "VARCHAR(500)", "Previous value"),
            ("new_value", "VARCHAR(500)", "New value"),
            ("reason", "TEXT", "Reason for change"),
            ("regulatory_filing_url", "VARCHAR(500)", "URL of regulatory filing"),
        ],
    },
    {
        "num": 24, "name": "Fund Mergers", "url": "/v1/mf/mergers",
        "freq": "Quarterly", "update": "Within 30 days of merger",
        "inputs": [("from_date", "Start"), ("to_date", "End")],
        "outputs": [
            ("merger_id", "BIGINT", "Primary key"),
            ("merging_scheme_code", "VARCHAR(20)", "Scheme being merged"),
            ("surviving_scheme_code", "VARCHAR(20)", "Resulting scheme"),
            ("merging_scheme_name", "VARCHAR(500)", "Merging scheme name"),
            ("surviving_scheme_name", "VARCHAR(500)", "Surviving scheme name"),
            ("merger_date", "DATE", "Effective merger date"),
            ("exchange_ratio", "VARCHAR(50)", "Unit exchange ratio"),
            ("aum_at_merger_cr", "NUMERIC(18,2)", "AUM at merger"),
            ("reason", "TEXT", "Reason for merger"),
        ],
    },
    {
        "num": 25, "name": "IDCW (Dividend) History", "url": "/v1/mf/{scheme_code}/idcw",
        "freq": "EOD", "update": "23:00 IST",
        "inputs": [
            ("scheme_code", "Scheme code"),
            ("from_date", "Start"),
            ("to_date", "End"),
        ],
        "outputs": [
            ("id", "BIGINT", "Primary key"),
            ("scheme_code", "VARCHAR(20)", "Scheme code"),
            ("announcement_date", "DATE", "Date announced"),
            ("record_date", "DATE", "Record date"),
            ("payment_date", "DATE", "Payment date"),
            ("idcw_per_unit", "NUMERIC(10,4)", "IDCW amount per unit"),
            ("idcw_type", "VARCHAR(30)", "Income/Capital Gains"),
            ("face_value", "NUMERIC(10,2)", "Face value reference"),
            ("nav_pre_idcw", "NUMERIC(14,4)", "NAV before IDCW"),
            ("nav_post_idcw", "NUMERIC(14,4)", "NAV after IDCW"),
        ],
    },
    {
        "num": 26, "name": "Portfolio Turnover", "url": "/v1/mf/{scheme_code}/turnover",
        "freq": "Monthly", "update": "7th of month",
        "inputs": [("scheme_code", "Scheme code"), ("from_month", "Start"), ("to_month", "End")],
        "outputs": [
            ("scheme_code", "VARCHAR(20)", "Scheme code"),
            ("as_of_month", "DATE", "Month end"),
            ("portfolio_turnover_ratio_pct", "NUMERIC(8,4)", "Portfolio turnover ratio"),
            ("avg_holding_period_months", "NUMERIC(8,4)", "Avg holding period implied"),
            ("category_avg_turnover_pct", "NUMERIC(8,4)", "Category avg turnover"),
        ],
    },
    {
        "num": 27, "name": "Historical Performance", "url": "/v1/mf/{scheme_code}/performance",
        "freq": "Daily", "update": "23:30 IST",
        "inputs": [
            ("scheme_code", "Scheme code"),
            ("from_date", "Start"),
            ("to_date", "End"),
            ("granularity", "daily/monthly/yearly"),
        ],
        "outputs": [
            ("scheme_code", "VARCHAR(20)", "Scheme code"),
            ("period_end_date", "DATE", "Period end"),
            ("nav", "NUMERIC(14,4)", "NAV at period end"),
            ("period_return_pct", "NUMERIC(10,4)", "Period return"),
            ("cumulative_return_pct", "NUMERIC(10,4)", "Cumulative return from start"),
            ("benchmark_period_return_pct", "NUMERIC(10,4)", "Benchmark return for period"),
            ("outperformance_pct", "NUMERIC(10,4)", "Outperformance vs benchmark"),
        ],
    },
    {
        "num": 28, "name": "Alpha", "url": "/v1/mf/{scheme_code}/alpha",
        "freq": "Daily", "update": "23:30 IST",
        "inputs": [
            ("scheme_code", "Scheme code"),
            ("as_of_date", "Date"),
            ("lookback_years", "Lookback (default 3)"),
        ],
        "outputs": [
            ("scheme_code", "VARCHAR(20)", "Scheme code"),
            ("as_of_date", "DATE", "Date"),
            ("alpha_pct", "NUMERIC(10,4)", "Jensen's alpha (annualized %)"),
            ("alpha_t_stat", "NUMERIC(8,4)", "T-statistic for alpha"),
            ("alpha_p_value", "NUMERIC(6,4)", "P-value (statistical significance)"),
            ("lookback_years", "SMALLINT", "Window used"),
        ],
    },
    {
        "num": 29, "name": "Beta", "url": "/v1/mf/{scheme_code}/beta",
        "freq": "Daily", "update": "23:30 IST",
        "inputs": [
            ("scheme_code", "Scheme code"),
            ("as_of_date", "Date"),
            ("benchmark", "Benchmark override"),
        ],
        "outputs": [
            ("scheme_code", "VARCHAR(20)", "Scheme code"),
            ("as_of_date", "DATE", "Date"),
            ("benchmark", "VARCHAR(200)", "Benchmark used"),
            ("beta", "NUMERIC(8,4)", "Beta vs benchmark"),
            ("upside_beta", "NUMERIC(8,4)", "Up-market beta"),
            ("downside_beta", "NUMERIC(8,4)", "Down-market beta"),
            ("lookback_years", "SMALLINT", "Window"),
        ],
    },
    {
        "num": 30, "name": "Sharpe Ratio", "url": "/v1/mf/{scheme_code}/sharpe",
        "freq": "Daily", "update": "23:30 IST",
        "inputs": [("scheme_code", "Scheme code"), ("as_of_date", "Date"), ("rf_rate", "Risk-free rate (default 7%)")],
        "outputs": [
            ("scheme_code", "VARCHAR(20)", "Scheme code"),
            ("as_of_date", "DATE", "Date"),
            ("sharpe_ratio", "NUMERIC(10,4)", "Sharpe ratio"),
            ("rf_rate_used_pct", "NUMERIC(8,4)", "Risk-free rate used"),
            ("category_avg_sharpe", "NUMERIC(10,4)", "Category average Sharpe"),
            ("rank_in_category", "INTEGER", "Rank in category"),
        ],
    },
    {
        "num": 31, "name": "Sortino Ratio", "url": "/v1/mf/{scheme_code}/sortino",
        "freq": "Daily", "update": "23:30 IST",
        "inputs": [("scheme_code", "Scheme code"), ("as_of_date", "Date")],
        "outputs": [
            ("scheme_code", "VARCHAR(20)", "Scheme code"),
            ("as_of_date", "DATE", "Date"),
            ("sortino_ratio", "NUMERIC(10,4)", "Sortino ratio"),
            ("downside_deviation_pct", "NUMERIC(10,4)", "Downside deviation"),
            ("rank_in_category", "INTEGER", "Rank in category"),
        ],
    },
    {
        "num": 32, "name": "Standard Deviation", "url": "/v1/mf/{scheme_code}/std-dev",
        "freq": "Daily", "update": "23:30 IST",
        "inputs": [("scheme_code", "Scheme code"), ("as_of_date", "Date"), ("lookback_years", "Window")],
        "outputs": [
            ("scheme_code", "VARCHAR(20)", "Scheme code"),
            ("as_of_date", "DATE", "Date"),
            ("std_dev_annualized_pct", "NUMERIC(10,4)", "Annualized std deviation"),
            ("std_dev_monthly_pct", "NUMERIC(10,4)", "Monthly std deviation"),
            ("category_avg_std_dev_pct", "NUMERIC(10,4)", "Category avg std dev"),
            ("rank_in_category", "INTEGER", "Rank"),
        ],
    },
    {
        "num": 33, "name": "Tracking Error", "url": "/v1/mf/{scheme_code}/tracking-error",
        "freq": "Daily", "update": "23:30 IST",
        "inputs": [("scheme_code", "Scheme code"), ("as_of_date", "Date")],
        "outputs": [
            ("scheme_code", "VARCHAR(20)", "Scheme code"),
            ("as_of_date", "DATE", "Date"),
            ("tracking_error_pct", "NUMERIC(10,4)", "Annualized tracking error vs benchmark"),
            ("information_ratio", "NUMERIC(10,4)", "Information ratio"),
            ("active_share_pct", "NUMERIC(8,4)", "Active share vs benchmark"),
        ],
    },
    {
        "num": 34, "name": "Fund Factsheet", "url": "/v1/mf/{scheme_code}/factsheet",
        "freq": "Monthly", "update": "10th of month",
        "inputs": [("scheme_code", "Scheme code"), ("as_of_month", "Month")],
        "outputs": [
            ("scheme_code", "VARCHAR(20)", "Scheme code"),
            ("as_of_month", "DATE", "Factsheet date"),
            ("nav", "NUMERIC(14,4)", "Month-end NAV"),
            ("aum_cr", "NUMERIC(18,2)", "Month-end AUM"),
            ("manager_name", "VARCHAR(255)", "Fund manager"),
            ("manager_tenure_years", "NUMERIC(6,2)", "Manager tenure"),
            ("expense_ratio_pct", "NUMERIC(6,4)", "Expense ratio"),
            ("returns_1y_pct", "NUMERIC(10,4)", "1-year return"),
            ("returns_3y_cagr_pct", "NUMERIC(10,4)", "3-year CAGR"),
            ("returns_5y_cagr_pct", "NUMERIC(10,4)", "5-year CAGR"),
            ("sharpe_ratio", "NUMERIC(10,4)", "Sharpe"),
            ("std_deviation_pct", "NUMERIC(10,4)", "Std dev"),
            ("beta", "NUMERIC(8,4)", "Beta"),
            ("top_10_holdings_weight_pct", "NUMERIC(8,4)", "Top 10 holdings weight"),
            ("equity_allocation_pct", "NUMERIC(8,4)", "Equity allocation"),
            ("debt_allocation_pct", "NUMERIC(8,4)", "Debt allocation"),
            ("cash_allocation_pct", "NUMERIC(8,4)", "Cash allocation"),
            ("factsheet_url", "VARCHAR(500)", "Official factsheet PDF URL"),
        ],
    },
    {
        "num": 35, "name": "Investor Flow", "url": "/v1/mf/{scheme_code}/flow",
        "freq": "Monthly", "update": "7th of month",
        "inputs": [("scheme_code", "Scheme code"), ("from_month", "Start"), ("to_month", "End")],
        "outputs": [
            ("scheme_code", "VARCHAR(20)", "Scheme code"),
            ("as_of_month", "DATE", "Month end"),
            ("gross_subscription_cr", "NUMERIC(18,2)", "Gross subscription"),
            ("gross_redemption_cr", "NUMERIC(18,2)", "Gross redemption"),
            ("net_flow_cr", "NUMERIC(18,2)", "Net flow"),
            ("aum_open_cr", "NUMERIC(18,2)", "AUM at month open"),
            ("aum_close_cr", "NUMERIC(18,2)", "AUM at month close"),
            ("aum_change_due_to_returns_cr", "NUMERIC(18,2)", "AUM change attributed to returns"),
            ("aum_change_due_to_flows_cr", "NUMERIC(18,2)", "AUM change due to net flows"),
            ("folio_count_open", "INTEGER", "Folios at month open"),
            ("folio_count_close", "INTEGER", "Folios at month close"),
            ("net_new_folios", "INTEGER", "Net new folios"),
        ],
    },
    {
        "num": 36, "name": "Fund Manager Tenure", "url": "/v1/mf/{scheme_code}/manager-tenure",
        "freq": "Monthly", "update": "7th of month",
        "inputs": [("scheme_code", "Scheme code")],
        "outputs": [
            ("scheme_code", "VARCHAR(20)", "Scheme code"),
            ("manager_name", "VARCHAR(255)", "Manager name"),
            ("managing_since", "DATE", "Date started managing this scheme"),
            ("tenure_years", "NUMERIC(6,2)", "Tenure in years"),
            ("return_during_tenure_pct", "NUMERIC(10,4)", "Return during tenure"),
            ("benchmark_return_during_tenure_pct", "NUMERIC(10,4)", "Benchmark return during tenure"),
            ("outperformance_pct", "NUMERIC(10,4)", "Outperformance during tenure"),
            ("is_current_manager", "BOOLEAN", "Currently managing flag"),
        ],
    },
    {
        "num": 37, "name": "Other Schemes by Same Manager", "url": "/v1/mf/manager/{manager_id}/schemes",
        "freq": "Monthly", "update": "7th of month",
        "inputs": [("manager_id", "Manager ID (path)")],
        "outputs": [
            ("manager_id", "BIGINT", "Manager primary key"),
            ("manager_name", "VARCHAR(255)", "Manager name"),
            ("scheme_code", "VARCHAR(20)", "Each managed scheme code"),
            ("scheme_name", "VARCHAR(500)", "Scheme name"),
            ("aum_cr", "NUMERIC(18,2)", "Scheme AUM"),
            ("returns_1y_pct", "NUMERIC(10,4)", "1y returns"),
            ("returns_3y_cagr_pct", "NUMERIC(10,4)", "3y CAGR"),
            ("manager_tenure_years", "NUMERIC(6,2)", "Tenure on this scheme"),
        ],
    },
    {
        "num": 38, "name": "NFO Calendar", "url": "/v1/mf/nfo",
        "freq": "Daily", "update": "22:30 IST",
        "inputs": [
            ("from_date", "Start"),
            ("to_date", "End"),
            ("category", "Filter by category"),
            ("status", "open/upcoming/closed"),
        ],
        "outputs": [
            ("nfo_id", "BIGINT", "Primary key"),
            ("scheme_name", "VARCHAR(500)", "New scheme name"),
            ("amc_name", "VARCHAR(255)", "AMC"),
            ("category", "VARCHAR(100)", "Category"),
            ("nfo_open_date", "DATE", "NFO open date"),
            ("nfo_close_date", "DATE", "NFO close date"),
            ("allotment_date", "DATE", "Allotment date"),
            ("reopen_date", "DATE", "Reopens for continuous subscription"),
            ("offer_price", "NUMERIC(14,4)", "NFO offer price"),
            ("min_investment", "NUMERIC(12,2)", "Min subscription"),
            ("benchmark_index", "VARCHAR(200)", "Benchmark"),
            ("manager_name", "VARCHAR(255)", "Fund manager"),
            ("status", "VARCHAR(20)", "upcoming/open/closed"),
            ("sid_url", "VARCHAR(500)", "Scheme Information Document URL"),
        ],
    },
    {
        "num": 39, "name": "Maturity Profile (Debt)", "url": "/v1/mf/{scheme_code}/maturity-profile",
        "freq": "Monthly", "update": "7th of month",
        "inputs": [("scheme_code", "Scheme code"), ("as_of_month", "Month")],
        "outputs": [
            ("scheme_code", "VARCHAR(20)", "Scheme code"),
            ("as_of_month", "DATE", "Month end"),
            ("modified_duration_years", "NUMERIC(8,4)", "Modified duration"),
            ("avg_maturity_years", "NUMERIC(8,4)", "Weighted avg maturity"),
            ("ytm_pct", "NUMERIC(8,4)", "Yield to maturity"),
            ("upto_1y_pct", "NUMERIC(8,4)", "% in instruments maturing <1 year"),
            ("1y_to_3y_pct", "NUMERIC(8,4)", "% in 1-3y maturity"),
            ("3y_to_5y_pct", "NUMERIC(8,4)", "% in 3-5y maturity"),
            ("5y_to_10y_pct", "NUMERIC(8,4)", "% in 5-10y maturity"),
            ("above_10y_pct", "NUMERIC(8,4)", "% in >10y maturity"),
        ],
    },
    {
        "num": 40, "name": "Credit Quality (Debt)", "url": "/v1/mf/{scheme_code}/credit-quality",
        "freq": "Monthly", "update": "7th of month",
        "inputs": [("scheme_code", "Scheme code"), ("as_of_month", "Month")],
        "outputs": [
            ("scheme_code", "VARCHAR(20)", "Scheme code"),
            ("as_of_month", "DATE", "Month end"),
            ("sovereign_pct", "NUMERIC(8,4)", "Sovereign / G-Sec %"),
            ("aaa_pct", "NUMERIC(8,4)", "AAA rated %"),
            ("aa_plus_pct", "NUMERIC(8,4)", "AA+ rated %"),
            ("aa_pct", "NUMERIC(8,4)", "AA rated %"),
            ("aa_minus_pct", "NUMERIC(8,4)", "AA- rated %"),
            ("a_pct", "NUMERIC(8,4)", "A rated %"),
            ("bbb_pct", "NUMERIC(8,4)", "BBB rated %"),
            ("below_bbb_pct", "NUMERIC(8,4)", "Below BBB %"),
            ("unrated_pct", "NUMERIC(8,4)", "Unrated %"),
            ("cash_pct", "NUMERIC(8,4)", "Cash & equivalents"),
            ("avg_credit_rating", "VARCHAR(10)", "Portfolio weighted average rating"),
        ],
    },
]
